package com.toyo.fish.data.wrapper.mail.domain;

import java.util.Date;

public class MailTriggerLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail_trigger_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail_trigger_log.mail_id
     *
     * @mbggenerated
     */
    private Long mailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail_trigger_log.reciever
     *
     * @mbggenerated
     */
    private Long reciever;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail_trigger_log.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail_trigger_log.category
     *
     * @mbggenerated
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail_trigger_log.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail_trigger_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;
    
    
    private Mail mail;
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail_trigger_log.id
     *
     * @return the value of ty_mail_trigger_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail_trigger_log.id
     *
     * @param id the value for ty_mail_trigger_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail_trigger_log.mail_id
     *
     * @return the value of ty_mail_trigger_log.mail_id
     *
     * @mbggenerated
     */
    public Long getMailId() {
        return mailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail_trigger_log.mail_id
     *
     * @param mailId the value for ty_mail_trigger_log.mail_id
     *
     * @mbggenerated
     */
    public void setMailId(Long mailId) {
        this.mailId = mailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail_trigger_log.reciever
     *
     * @return the value of ty_mail_trigger_log.reciever
     *
     * @mbggenerated
     */
    public Long getReciever() {
        return reciever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail_trigger_log.reciever
     *
     * @param reciever the value for ty_mail_trigger_log.reciever
     *
     * @mbggenerated
     */
    public void setReciever(Long reciever) {
        this.reciever = reciever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail_trigger_log.state
     *
     * @return the value of ty_mail_trigger_log.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail_trigger_log.state
     *
     * @param state the value for ty_mail_trigger_log.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail_trigger_log.category
     *
     * @return the value of ty_mail_trigger_log.category
     *
     * @mbggenerated
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail_trigger_log.category
     *
     * @param category the value for ty_mail_trigger_log.category
     *
     * @mbggenerated
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail_trigger_log.update_time
     *
     * @return the value of ty_mail_trigger_log.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail_trigger_log.update_time
     *
     * @param updateTime the value for ty_mail_trigger_log.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail_trigger_log.create_time
     *
     * @return the value of ty_mail_trigger_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail_trigger_log.create_time
     *
     * @param createTime the value for ty_mail_trigger_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	public Mail getMail() {
		return mail;
	}

	public void setMail(Mail mail) {
		this.mail = mail;
	}



}
