package com.toyo.fish.data.wrapper.mail.domain;

import java.util.Date;

public class MailTriggerUserInformation implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -5460725387354890531L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail_trigger_user_information.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail_trigger_user_information.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail_trigger_user_information.last_login
     *
     * @mbggenerated
     */
    private Date lastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail_trigger_user_information.last_apk_version
     *
     * @mbggenerated
     */
    private Integer lastApkVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail_trigger_user_information.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail_trigger_user_information.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail_trigger_user_information.id
     *
     * @return the value of ty_mail_trigger_user_information.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail_trigger_user_information.id
     *
     * @param id the value for ty_mail_trigger_user_information.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail_trigger_user_information.user_id
     *
     * @return the value of ty_mail_trigger_user_information.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail_trigger_user_information.user_id
     *
     * @param userId the value for ty_mail_trigger_user_information.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail_trigger_user_information.last_login
     *
     * @return the value of ty_mail_trigger_user_information.last_login
     *
     * @mbggenerated
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail_trigger_user_information.last_login
     *
     * @param lastLogin the value for ty_mail_trigger_user_information.last_login
     *
     * @mbggenerated
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail_trigger_user_information.last_apk_version
     *
     * @return the value of ty_mail_trigger_user_information.last_apk_version
     *
     * @mbggenerated
     */
    public Integer getLastApkVersion() {
        return lastApkVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail_trigger_user_information.last_apk_version
     *
     * @param lastApkVersion the value for ty_mail_trigger_user_information.last_apk_version
     *
     * @mbggenerated
     */
    public void setLastApkVersion(Integer lastApkVersion) {
        this.lastApkVersion = lastApkVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail_trigger_user_information.update_time
     *
     * @return the value of ty_mail_trigger_user_information.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail_trigger_user_information.update_time
     *
     * @param updateTime the value for ty_mail_trigger_user_information.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail_trigger_user_information.create_time
     *
     * @return the value of ty_mail_trigger_user_information.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail_trigger_user_information.create_time
     *
     * @param createTime the value for ty_mail_trigger_user_information.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}