package com.toyo.fish.data.wrapper.mail.domain;

import java.util.Date;

public class Mail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail.sender
     *
     * @mbggenerated
     */
    private Long sender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail.category
     *
     * @mbggenerated
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail.attachment_state
     *
     * @mbggenerated
     */
    private Integer attachmentState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail.attachments
     *
     * @mbggenerated
     */
    private String attachments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail.time_trigger_expression
     *
     * @mbggenerated
     */
    private String timeTriggerExpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail.active_hours
     *
     * @mbggenerated
     */
    private Integer activeHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail.trigger_expression
     *
     * @mbggenerated
     */
    private String triggerExpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail.filter_state
     *
     * @mbggenerated
     */
    private Integer filterState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail.cleanup_state
     *
     * @mbggenerated
     */
    private Integer cleanupState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_mail.create_time
     *
     * @mbggenerated
     */
    private Date createTime;
    
    private Long reciever;
    private Integer inQueueState;

    public Long getReciever() {
		return reciever;
	}

	public void setReciever(Long reciever) {
		this.reciever = reciever;
	}

	public Integer getInQueueState() {
		return inQueueState;
	}

	public void setInQueueState(Integer inQueueState) {
		this.inQueueState = inQueueState;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail.id
     *
     * @return the value of ty_mail.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail.id
     *
     * @param id the value for ty_mail.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail.title
     *
     * @return the value of ty_mail.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail.title
     *
     * @param title the value for ty_mail.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail.sender
     *
     * @return the value of ty_mail.sender
     *
     * @mbggenerated
     */
    public Long getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail.sender
     *
     * @param sender the value for ty_mail.sender
     *
     * @mbggenerated
     */
    public void setSender(Long sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail.content
     *
     * @return the value of ty_mail.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail.content
     *
     * @param content the value for ty_mail.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail.category
     *
     * @return the value of ty_mail.category
     *
     * @mbggenerated
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail.category
     *
     * @param category the value for ty_mail.category
     *
     * @mbggenerated
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail.attachment_state
     *
     * @return the value of ty_mail.attachment_state
     *
     * @mbggenerated
     */
    public Integer getAttachmentState() {
        return attachmentState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail.attachment_state
     *
     * @param attachmentState the value for ty_mail.attachment_state
     *
     * @mbggenerated
     */
    public void setAttachmentState(Integer attachmentState) {
        this.attachmentState = attachmentState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail.attachments
     *
     * @return the value of ty_mail.attachments
     *
     * @mbggenerated
     */
    public String getAttachments() {
        return attachments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail.attachments
     *
     * @param attachments the value for ty_mail.attachments
     *
     * @mbggenerated
     */
    public void setAttachments(String attachments) {
        this.attachments = attachments == null ? null : attachments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail.time_trigger_expression
     *
     * @return the value of ty_mail.time_trigger_expression
     *
     * @mbggenerated
     */
    public String getTimeTriggerExpression() {
        return timeTriggerExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail.time_trigger_expression
     *
     * @param timeTriggerExpression the value for ty_mail.time_trigger_expression
     *
     * @mbggenerated
     */
    public void setTimeTriggerExpression(String timeTriggerExpression) {
        this.timeTriggerExpression = timeTriggerExpression == null ? null : timeTriggerExpression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail.active_hours
     *
     * @return the value of ty_mail.active_hours
     *
     * @mbggenerated
     */
    public Integer getActiveHours() {
        return activeHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail.active_hours
     *
     * @param activeHours the value for ty_mail.active_hours
     *
     * @mbggenerated
     */
    public void setActiveHours(Integer activeHours) {
        this.activeHours = activeHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail.trigger_expression
     *
     * @return the value of ty_mail.trigger_expression
     *
     * @mbggenerated
     */
    public String getTriggerExpression() {
        return triggerExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail.trigger_expression
     *
     * @param triggerExpression the value for ty_mail.trigger_expression
     *
     * @mbggenerated
     */
    public void setTriggerExpression(String triggerExpression) {
        this.triggerExpression = triggerExpression == null ? null : triggerExpression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail.filter_state
     *
     * @return the value of ty_mail.filter_state
     *
     * @mbggenerated
     */
    public Integer getFilterState() {
        return filterState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail.filter_state
     *
     * @param filterState the value for ty_mail.filter_state
     *
     * @mbggenerated
     */
    public void setFilterState(Integer filterState) {
        this.filterState = filterState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail.cleanup_state
     *
     * @return the value of ty_mail.cleanup_state
     *
     * @mbggenerated
     */
    public Integer getCleanupState() {
        return cleanupState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail.cleanup_state
     *
     * @param cleanupState the value for ty_mail.cleanup_state
     *
     * @mbggenerated
     */
    public void setCleanupState(Integer cleanupState) {
        this.cleanupState = cleanupState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail.update_time
     *
     * @return the value of ty_mail.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail.update_time
     *
     * @param updateTime the value for ty_mail.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_mail.create_time
     *
     * @return the value of ty_mail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_mail.create_time
     *
     * @param createTime the value for ty_mail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}