package com.toyo.fish.data.wrapper.persistence;

import org.apache.ibatis.annotations.Param;

import com.toyo.fish.data.wrapper.domain.ApkVersionUpdateLog;

public interface ApkVersionUpdateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_apk_version_update_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_apk_version_update_log
     *
     * @mbggenerated
     */
    int insert(ApkVersionUpdateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_apk_version_update_log
     *
     * @mbggenerated
     */
    int insertSelective(ApkVersionUpdateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_apk_version_update_log
     *
     * @mbggenerated
     */
    ApkVersionUpdateLog selectByPrimaryKey(Long id);
    
    /**
     * 
     * @param userId
     * @param apkVersion
     * @return
     */
    Integer selectByUserIdAndApkVersion(@Param("userId") Long userId,@Param("apkVersion") String apkVersion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_apk_version_update_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApkVersionUpdateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_apk_version_update_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApkVersionUpdateLog record);
}