package com.toyo.fish.data.wrapper.persistence;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.toyo.fish.data.wrapper.domain.Login;

public interface LoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_login
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_login
     *
     * @mbggenerated
     */
    int insert(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_login
     *
     * @mbggenerated
     */
    int insertSelective(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_login
     *
     * @mbggenerated
     */
    Login selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Login record);
    
    
    
    Login findLoginByUserId(@Param("userId") Long usrId);
    
    @Select("select * from ty_login where device_id=#{deviceId} order by id desc limit 0,1")
    @ResultMap("BaseResultMap")
    Login findLoginByDeviceId(@Param("deviceId") String deviceId);
    
   
    void deleteByDeviceId(@Param("deviceId") String deviceId);
    
    
}