package com.toyo.fish.data.wrapper.persistence;

import com.toyo.fish.data.wrapper.domain.ThirdPartyAccount;

public interface ThirdPartyAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_third_party_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_third_party_account
     *
     * @mbggenerated
     */
    int insert(ThirdPartyAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_third_party_account
     *
     * @mbggenerated
     */
    int insertSelective(ThirdPartyAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_third_party_account
     *
     * @mbggenerated
     */
    ThirdPartyAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_third_party_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ThirdPartyAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_third_party_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ThirdPartyAccount record);
    
    
    
    ThirdPartyAccount findThirdPartyAccountByUserId(Long userId);
}