package com.toyo.fish.data.wrapper.persistence;

import org.apache.ibatis.annotations.Param;

import com.toyo.fish.data.wrapper.domain.UserBan;

public interface UserBanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_user_ban
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_user_ban
     *
     * @mbggenerated
     */
    int insert(UserBan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_user_ban
     *
     * @mbggenerated
     */
    int insertSelective(UserBan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_user_ban
     *
     * @mbggenerated
     */
    UserBan selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_user_ban
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserBan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_user_ban
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserBan record);
    
    
    UserBan selectByDeviceIdAndChannelId(@Param("deviceId") String deviceId,@Param("channelId") Integer channelId);
}