package com.toyo.fish.data.wrapper.persistence;

import com.toyo.fish.data.wrapper.domain.ValidCode;

public interface ValidCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_valid_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_valid_code
     *
     * @mbggenerated
     */
    int insert(ValidCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_valid_code
     *
     * @mbggenerated
     */
    int insertSelective(ValidCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_valid_code
     *
     * @mbggenerated
     */
    ValidCode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_valid_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ValidCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_valid_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ValidCode record);
    
    
    
    /**
     * find valid code of the userid
     * 
     * @param userId
     * @return
     */
    ValidCode findValidCodeByUserId(Long userId);
    
    
    
    
    
    
}