package com.toyo.fish.data.wrapper.persistence;

import com.toyo.fish.data.wrapper.domain.Zone;

public interface ZoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_zone
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_zone
     *
     * @mbggenerated
     */
    int insert(Zone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_zone
     *
     * @mbggenerated
     */
    int insertSelective(Zone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_zone
     *
     * @mbggenerated
     */
    Zone selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_zone
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Zone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_zone
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Zone record);
    
    
    
    Zone findZoneByActive();
}