package com.sky.mobile.protocol.persistence;

import com.sky.mobile.protocol.domain.AnZhiNotify;

public interface AnZhiNotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_anzhi_notify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_anzhi_notify
     *
     * @mbggenerated
     */
    int insert(AnZhiNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_anzhi_notify
     *
     * @mbggenerated
     */
    int insertSelective(AnZhiNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_anzhi_notify
     *
     * @mbggenerated
     */
    AnZhiNotify selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_anzhi_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnZhiNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_anzhi_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AnZhiNotify record);
}