package com.sky.mobile.protocol.persistence;

import com.sky.mobile.protocol.domain.BaiduNotify;

public interface BaiduNotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_baidu_notify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_baidu_notify
     *
     * @mbggenerated
     */
    int insert(BaiduNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_baidu_notify
     *
     * @mbggenerated
     */
    int insertSelective(BaiduNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_baidu_notify
     *
     * @mbggenerated
     */
    BaiduNotify selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_baidu_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaiduNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_baidu_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaiduNotify record);
}