package com.sky.mobile.protocol.persistence;

import com.sky.mobile.protocol.domain.FlymeNotify;

public interface FlymeNotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_flyme_notify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_flyme_notify
     *
     * @mbggenerated
     */
    int insert(FlymeNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_flyme_notify
     *
     * @mbggenerated
     */
    int insertSelective(FlymeNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_flyme_notify
     *
     * @mbggenerated
     */
    FlymeNotify selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_flyme_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FlymeNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_flyme_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FlymeNotify record);
}