package com.sky.mobile.protocol.persistence;

import com.sky.mobile.protocol.domain.HuaweiNotify;

public interface HuaweiNotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_huawei_notify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_huawei_notify
     *
     * @mbggenerated
     */
    int insert(HuaweiNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_huawei_notify
     *
     * @mbggenerated
     */
    int insertSelective(HuaweiNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_huawei_notify
     *
     * @mbggenerated
     */
    HuaweiNotify selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_huawei_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HuaweiNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_huawei_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HuaweiNotify record);
}