package com.sky.mobile.protocol.persistence;

import com.sky.mobile.protocol.domain.JinliNotify;

public interface JinliNotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_jinli_notify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_jinli_notify
     *
     * @mbggenerated
     */
    int insert(JinliNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_jinli_notify
     *
     * @mbggenerated
     */
    int insertSelective(JinliNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_jinli_notify
     *
     * @mbggenerated
     */
    JinliNotify selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_jinli_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JinliNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_jinli_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JinliNotify record);
}