package com.sky.mobile.protocol.persistence;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.sky.mobile.protocol.domain.LenovoGetOrder;

public interface LenovoGetOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lenovo_get_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lenovo_get_order
     *
     * @mbggenerated
     */
    int insert(LenovoGetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lenovo_get_order
     *
     * @mbggenerated
     */
    int insertSelective(LenovoGetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lenovo_get_order
     *
     * @mbggenerated
     */
    LenovoGetOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lenovo_get_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LenovoGetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lenovo_get_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LenovoGetOrder record);
    
    
    
    @Select("select * from tbl_lenovo_get_order where order_id=#{orderId}")
    @ResultMap("BaseResultMap")
    LenovoGetOrder findByOrderId(@Param("orderId") String orderId);
    
}