package com.sky.mobile.protocol.persistence;

import com.sky.mobile.protocol.domain.OppNotify;

public interface OppNotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_opp_notify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_opp_notify
     *
     * @mbggenerated
     */
    int insert(OppNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_opp_notify
     *
     * @mbggenerated
     */
    int insertSelective(OppNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_opp_notify
     *
     * @mbggenerated
     */
    OppNotify selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_opp_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OppNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_opp_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OppNotify record);
}