package com.sky.mobile.protocol.persistence;

import com.sky.mobile.protocol.domain.Qqnotify;

public interface QqnotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_qq_notify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_qq_notify
     *
     * @mbggenerated
     */
    int insert(Qqnotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_qq_notify
     *
     * @mbggenerated
     */
    int insertSelective(Qqnotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_qq_notify
     *
     * @mbggenerated
     */
    Qqnotify selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_qq_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Qqnotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_qq_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Qqnotify record);
}