package com.sky.mobile.protocol.persistence;

import com.sky.mobile.protocol.domain.SafeCenterNotify;

public interface SafeCenterNotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_safe_center_notify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_safe_center_notify
     *
     * @mbggenerated
     */
    int insert(SafeCenterNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_safe_center_notify
     *
     * @mbggenerated
     */
    int insertSelective(SafeCenterNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_safe_center_notify
     *
     * @mbggenerated
     */
    SafeCenterNotify selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_safe_center_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SafeCenterNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_safe_center_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SafeCenterNotify record);
}