package com.sky.mobile.protocol.persistence;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.sky.mobile.protocol.domain.VivoGetOrder;

public interface VivoGetOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_vivo_get_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_vivo_get_order
     *
     * @mbggenerated
     */
    int insert(VivoGetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_vivo_get_order
     *
     * @mbggenerated
     */
    int insertSelective(VivoGetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_vivo_get_order
     *
     * @mbggenerated
     */
    VivoGetOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_vivo_get_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VivoGetOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_vivo_get_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VivoGetOrder record);
    
    
    @Select("select * from tbl_vivo_get_order where local_order_id=#{local_order_id} ")
    @ResultMap("BaseResultMap")
    VivoGetOrder findByLocalOrderId(@Param("local_order_id") String localOrderId);
    
}