package com.sky.mobile.protocol.persistence;

import com.sky.mobile.protocol.domain.WdjNotify;

public interface WdjNotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wdj_notify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wdj_notify
     *
     * @mbggenerated
     */
    int insert(WdjNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wdj_notify
     *
     * @mbggenerated
     */
    int insertSelective(WdjNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wdj_notify
     *
     * @mbggenerated
     */
    WdjNotify selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wdj_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WdjNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_wdj_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WdjNotify record);
}