package com.toyo.fish.data.wrapper.zone.persistence;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.toyo.fish.data.wrapper.zone.domain.CurrencyLog;

public interface CurrencyLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_currency_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);
    
    
    /**
     * 
     * @param userId
     * @return
     */
    int deleteByUserId(@Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_currency_log
     *
     * @mbggenerated
     */
    int insert(CurrencyLog record);
    
    /**
     * 
     * @return
     */
    int insertBySelectUserId(@Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_currency_log
     *
     * @mbggenerated
     */
    int insertSelective(CurrencyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_currency_log
     *
     * @mbggenerated
     */
    CurrencyLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_currency_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CurrencyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_currency_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CurrencyLog record);
    
    
    
    int saveCurrencyLogBatch(@Param("records") List<CurrencyLog> records);
    
    
}