package com.toyo.fish.data.wrapper.zone.persistence;

import org.apache.ibatis.annotations.Param;

import com.toyo.fish.data.wrapper.zone.domain.FishFarmJoinLog;

public interface FishFarmJoinLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_fish_farm_join_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);
    
    
    int deleteByUserId(@Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_fish_farm_join_log
     *
     * @mbggenerated
     */
    int insert(FishFarmJoinLog record);
    
    /**
     * 
     * @param userId
     * @return
     */
    int insertBySelectUserId(@Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_fish_farm_join_log
     *
     * @mbggenerated
     */
    int insertSelective(FishFarmJoinLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_fish_farm_join_log
     *
     * @mbggenerated
     */
    FishFarmJoinLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_fish_farm_join_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FishFarmJoinLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_fish_farm_join_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FishFarmJoinLog record);
}