package com.toyo.fish.data.wrapper.zone.persistence;

import org.apache.ibatis.annotations.Param;

import com.toyo.fish.data.wrapper.zone.domain.FishEquipmentLog;

public interface FishEquipmentLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_fish_equipment_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);
    
    
    int deleteByUserId(@Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_fish_equipment_log
     *
     * @mbggenerated
     */
    int insert(FishEquipmentLog record);
    
    
    int insertBySelectUserId(@Param("userId") Long  userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_fish_equipment_log
     *
     * @mbggenerated
     */
    int insertSelective(FishEquipmentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_fish_equipment_log
     *
     * @mbggenerated
     */
    FishEquipmentLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_fish_equipment_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FishEquipmentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_fish_equipment_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FishEquipmentLog record);
    
    
    FishEquipmentLog selectByWeightLogId(Long fishWeightId);
    
    FishEquipmentLog selectByWeightFailedLogId(Long fishWeightId);
}