package com.toyo.fish.data.wrapper.zone.persistence;

import org.apache.ibatis.annotations.Param;

import com.toyo.fish.data.wrapper.zone.domain.FishWeightFailedLog;

public interface FishWeightFailedLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_fish_weight_failed_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);
    
    /**
     * 
     * @param userId
     * @return
     */
    int deleteByUserId(@Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_fish_weight_failed_log
     *
     * @mbggenerated
     */
    int insert(FishWeightFailedLog record);
    
    /**
     * 
     * @param userId
     * @return
     */
    int insertBySelectUserId(@Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_fish_weight_failed_log
     *
     * @mbggenerated
     */
    int insertSelective(FishWeightFailedLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_fish_weight_failed_log
     *
     * @mbggenerated
     */
    FishWeightFailedLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_fish_weight_failed_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FishWeightFailedLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_fish_weight_failed_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FishWeightFailedLog record);
    
    
    FishWeightFailedLog findFishWeighFailedtByUserIdAndFishId(@Param("userId") Long userId,@Param("fishId") String fishId);
}