package com.toyo.fish.data.wrapper.zone.persistence;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.toyo.fish.data.wrapper.zone.domain.VitLog;

public interface VitLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_vit_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);
    
    
    int deleteByUserId(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_vit_log
     *
     * @mbggenerated
     */
    int insert(VitLog record);
    
    /**
     * 
     * @param userId
     * @return
     */
    int insertBySelectUserId(@Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_vit_log
     *
     * @mbggenerated
     */
    int insertSelective(VitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_vit_log
     *
     * @mbggenerated
     */
    VitLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_vit_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_vit_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VitLog record);
    
    
    int insertBatch(@Param("records") List<VitLog> records);
}