package com.toyo.fish.data.wrapper.mail.persistence;

import org.apache.ibatis.annotations.Param;

import com.toyo.fish.data.wrapper.mail.domain.MailTriggerUserInformation;

public interface MailTriggerUserInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_mail_trigger_user_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_mail_trigger_user_information
     *
     * @mbggenerated
     */
    int insert(MailTriggerUserInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_mail_trigger_user_information
     *
     * @mbggenerated
     */
    int insertSelective(MailTriggerUserInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_mail_trigger_user_information
     *
     * @mbggenerated
     */
    MailTriggerUserInformation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_mail_trigger_user_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MailTriggerUserInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_mail_trigger_user_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MailTriggerUserInformation record);
    
    /**
     * 
     * @param userId
     * @return
     */
    MailTriggerUserInformation selectByUserId(Long userId);
    
    
   int  deleteByUserId(@Param("userId") Long userId);
    
}