package com.toyo.fish.data.wrapper.system.domain;

public class ExchangeCodeItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_exchange_code_item.gift_id
     *
     * @mbggenerated
     */
    private Integer giftId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_exchange_code_item.item_id
     *
     * @mbggenerated
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_exchange_code_item.item_total
     *
     * @mbggenerated
     */
    private Integer itemTotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_exchange_code_item.gift_id
     *
     * @return the value of ty_exchange_code_item.gift_id
     *
     * @mbggenerated
     */
    public Integer getGiftId() {
        return giftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_exchange_code_item.gift_id
     *
     * @param giftId the value for ty_exchange_code_item.gift_id
     *
     * @mbggenerated
     */
    public void setGiftId(Integer giftId) {
        this.giftId = giftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_exchange_code_item.item_id
     *
     * @return the value of ty_exchange_code_item.item_id
     *
     * @mbggenerated
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_exchange_code_item.item_id
     *
     * @param itemId the value for ty_exchange_code_item.item_id
     *
     * @mbggenerated
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_exchange_code_item.item_total
     *
     * @return the value of ty_exchange_code_item.item_total
     *
     * @mbggenerated
     */
    public Integer getItemTotal() {
        return itemTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_exchange_code_item.item_total
     *
     * @param itemTotal the value for ty_exchange_code_item.item_total
     *
     * @mbggenerated
     */
    public void setItemTotal(Integer itemTotal) {
        this.itemTotal = itemTotal;
    }
}