package com.toyo.fish.data.wrapper.system.domain;

import java.util.Date;
import java.util.List;

public class ExchangeCodeGift {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_exchange_code_gift.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_exchange_code_gift.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_exchange_code_gift.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_exchange_code_gift.create_time
     *
     * @mbggenerated
     */
    private Date createTime;
    
    // 礼包中的物品列表
    private List<ExchangeCodeItem> items;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_exchange_code_gift.id
     *
     * @return the value of ty_exchange_code_gift.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_exchange_code_gift.id
     *
     * @param id the value for ty_exchange_code_gift.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_exchange_code_gift.name
     *
     * @return the value of ty_exchange_code_gift.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_exchange_code_gift.name
     *
     * @param name the value for ty_exchange_code_gift.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_exchange_code_gift.state
     *
     * @return the value of ty_exchange_code_gift.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_exchange_code_gift.state
     *
     * @param state the value for ty_exchange_code_gift.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_exchange_code_gift.create_time
     *
     * @return the value of ty_exchange_code_gift.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_exchange_code_gift.create_time
     *
     * @param createTime the value for ty_exchange_code_gift.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	public List<ExchangeCodeItem> getItems() {
		return items;
	}

	public void setItems(List<ExchangeCodeItem> items) {
		this.items = items;
	}
    
    
}