package com.toyo.fish.data.wrapper.system.domain;

import java.util.Date;
import java.util.List;

public class ResourceUpdate implements java.io.Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 4561821151926112904L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_resource_update.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_resource_update.channel_id
     *
     * @mbggenerated
     */
    private Long channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_resource_update.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_resource_update.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_resource_update.md5
     *
     * @mbggenerated
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_resource_update.active
     *
     * @mbggenerated
     */
    private Integer active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_resource_update.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_resource_update.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_resource_update.force_update
     *
     * @mbggenerated
     */
    private Integer forceUpdate;
    
    
    List<ResourceFiles> files;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_resource_update.id
     *
     * @return the value of ty_resource_update.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_resource_update.id
     *
     * @param id the value for ty_resource_update.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_resource_update.channel_id
     *
     * @return the value of ty_resource_update.channel_id
     *
     * @mbggenerated
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_resource_update.channel_id
     *
     * @param channelId the value for ty_resource_update.channel_id
     *
     * @mbggenerated
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_resource_update.version
     *
     * @return the value of ty_resource_update.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_resource_update.version
     *
     * @param version the value for ty_resource_update.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_resource_update.url
     *
     * @return the value of ty_resource_update.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_resource_update.url
     *
     * @param url the value for ty_resource_update.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_resource_update.md5
     *
     * @return the value of ty_resource_update.md5
     *
     * @mbggenerated
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_resource_update.md5
     *
     * @param md5 the value for ty_resource_update.md5
     *
     * @mbggenerated
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_resource_update.active
     *
     * @return the value of ty_resource_update.active
     *
     * @mbggenerated
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_resource_update.active
     *
     * @param active the value for ty_resource_update.active
     *
     * @mbggenerated
     */
    public void setActive(Integer active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_resource_update.create_time
     *
     * @return the value of ty_resource_update.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_resource_update.create_time
     *
     * @param createTime the value for ty_resource_update.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_resource_update.update_time
     *
     * @return the value of ty_resource_update.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_resource_update.update_time
     *
     * @param updateTime the value for ty_resource_update.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_resource_update.force_update
     *
     * @return the value of ty_resource_update.force_update
     *
     * @mbggenerated
     */
    public Integer getForceUpdate() {
        return forceUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_resource_update.force_update
     *
     * @param forceUpdate the value for ty_resource_update.force_update
     *
     * @mbggenerated
     */
    public void setForceUpdate(Integer forceUpdate) {
        this.forceUpdate = forceUpdate;
    }

	public List<ResourceFiles> getFiles() {
		return files;
	}

	public void setFiles(List<ResourceFiles> files) {
		this.files = files;
	}
    
    
    
}