package com.toyo.fish.data.wrapper.system.domain;

import java.util.Date;

public class ResourceFiles  implements java.io.Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -3525078925261208066L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_resource_files.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_resource_files.resource_update_id
     *
     * @mbggenerated
     */
    private Long resourceUpdateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_resource_files.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_resource_files.md5
     *
     * @mbggenerated
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_resource_files.size
     *
     * @mbggenerated
     */
    private Integer size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_resource_files.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_resource_files.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_resource_files.id
     *
     * @return the value of ty_resource_files.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_resource_files.id
     *
     * @param id the value for ty_resource_files.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_resource_files.resource_update_id
     *
     * @return the value of ty_resource_files.resource_update_id
     *
     * @mbggenerated
     */
    public Long getResourceUpdateId() {
        return resourceUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_resource_files.resource_update_id
     *
     * @param resourceUpdateId the value for ty_resource_files.resource_update_id
     *
     * @mbggenerated
     */
    public void setResourceUpdateId(Long resourceUpdateId) {
        this.resourceUpdateId = resourceUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_resource_files.url
     *
     * @return the value of ty_resource_files.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_resource_files.url
     *
     * @param url the value for ty_resource_files.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_resource_files.md5
     *
     * @return the value of ty_resource_files.md5
     *
     * @mbggenerated
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_resource_files.md5
     *
     * @param md5 the value for ty_resource_files.md5
     *
     * @mbggenerated
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_resource_files.size
     *
     * @return the value of ty_resource_files.size
     *
     * @mbggenerated
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_resource_files.size
     *
     * @param size the value for ty_resource_files.size
     *
     * @mbggenerated
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_resource_files.create_time
     *
     * @return the value of ty_resource_files.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_resource_files.create_time
     *
     * @param createTime the value for ty_resource_files.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_resource_files.update_time
     *
     * @return the value of ty_resource_files.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_resource_files.update_time
     *
     * @param updateTime the value for ty_resource_files.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}