package com.toyo.fish.data.wrapper.zone.domain;

import java.util.Date;

public class CurrencyLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_currency_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_currency_log.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_currency_log.f_module
     *
     * @mbggenerated
     */
    private Integer fModule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_currency_log.f_action
     *
     * @mbggenerated
     */
    private Integer fAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_currency_log.f_param
     *
     * @mbggenerated
     */
    private Integer fParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_currency_log.f_category
     *
     * @mbggenerated
     */
    private Integer fCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_currency_log.f_amount
     *
     * @mbggenerated
     */
    private Integer fAmount;
    
    
    private Long clientId;

    public Long getClientId() {
		return clientId;
	}

	public void setClientId(Long clientId) {
		this.clientId = clientId;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_currency_log.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_currency_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_currency_log.id
     *
     * @return the value of ty_currency_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_currency_log.id
     *
     * @param id the value for ty_currency_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_currency_log.user_id
     *
     * @return the value of ty_currency_log.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_currency_log.user_id
     *
     * @param userId the value for ty_currency_log.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_currency_log.f_module
     *
     * @return the value of ty_currency_log.f_module
     *
     * @mbggenerated
     */
    public Integer getfModule() {
        return fModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_currency_log.f_module
     *
     * @param fModule the value for ty_currency_log.f_module
     *
     * @mbggenerated
     */
    public void setfModule(Integer fModule) {
        this.fModule = fModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_currency_log.f_action
     *
     * @return the value of ty_currency_log.f_action
     *
     * @mbggenerated
     */
    public Integer getfAction() {
        return fAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_currency_log.f_action
     *
     * @param fAction the value for ty_currency_log.f_action
     *
     * @mbggenerated
     */
    public void setfAction(Integer fAction) {
        this.fAction = fAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_currency_log.f_param
     *
     * @return the value of ty_currency_log.f_param
     *
     * @mbggenerated
     */
    public Integer getfParam() {
        return fParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_currency_log.f_param
     *
     * @param fParam the value for ty_currency_log.f_param
     *
     * @mbggenerated
     */
    public void setfParam(Integer fParam) {
        this.fParam = fParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_currency_log.f_category
     *
     * @return the value of ty_currency_log.f_category
     *
     * @mbggenerated
     */
    public Integer getfCategory() {
        return fCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_currency_log.f_category
     *
     * @param fCategory the value for ty_currency_log.f_category
     *
     * @mbggenerated
     */
    public void setfCategory(Integer fCategory) {
        this.fCategory = fCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_currency_log.f_amount
     *
     * @return the value of ty_currency_log.f_amount
     *
     * @mbggenerated
     */
    public Integer getfAmount() {
        return fAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_currency_log.f_amount
     *
     * @param fAmount the value for ty_currency_log.f_amount
     *
     * @mbggenerated
     */
    public void setfAmount(Integer fAmount) {
        this.fAmount = fAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_currency_log.update_time
     *
     * @return the value of ty_currency_log.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_currency_log.update_time
     *
     * @param updateTime the value for ty_currency_log.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_currency_log.create_time
     *
     * @return the value of ty_currency_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_currency_log.create_time
     *
     * @param createTime the value for ty_currency_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}