package com.toyo.fish.data.wrapper.zone.domain;

import java.util.Date;

public class FishFarmJoinLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_farm_join_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_farm_join_log.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_farm_join_log.farm_id
     *
     * @mbggenerated
     */
    private String farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_farm_join_log.log_type
     *
     * @mbggenerated
     */
    private Integer logType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_farm_join_log.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_farm_join_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_farm_join_log.id
     *
     * @return the value of ty_fish_farm_join_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_farm_join_log.id
     *
     * @param id the value for ty_fish_farm_join_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_farm_join_log.user_id
     *
     * @return the value of ty_fish_farm_join_log.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_farm_join_log.user_id
     *
     * @param userId the value for ty_fish_farm_join_log.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_farm_join_log.farm_id
     *
     * @return the value of ty_fish_farm_join_log.farm_id
     *
     * @mbggenerated
     */
    public String getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_farm_join_log.farm_id
     *
     * @param farmId the value for ty_fish_farm_join_log.farm_id
     *
     * @mbggenerated
     */
    public void setFarmId(String farmId) {
        this.farmId = farmId == null ? null : farmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_farm_join_log.log_type
     *
     * @return the value of ty_fish_farm_join_log.log_type
     *
     * @mbggenerated
     */
    public Integer getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_farm_join_log.log_type
     *
     * @param logType the value for ty_fish_farm_join_log.log_type
     *
     * @mbggenerated
     */
    public void setLogType(Integer logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_farm_join_log.update_time
     *
     * @return the value of ty_fish_farm_join_log.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_farm_join_log.update_time
     *
     * @param updateTime the value for ty_fish_farm_join_log.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_farm_join_log.create_time
     *
     * @return the value of ty_fish_farm_join_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_farm_join_log.create_time
     *
     * @param createTime the value for ty_fish_farm_join_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}