package com.toyo.fish.data.wrapper.zone.domain;

import java.math.BigDecimal;
import java.util.Date;

public class FishWeightLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_weight_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_weight_log.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_weight_log.fish_id
     *
     * @mbggenerated
     */
    private String fishId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_weight_log.grade
     *
     * @mbggenerated
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_weight_log.rare
     *
     * @mbggenerated
     */
    private Integer rare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_weight_log.weight
     *
     * @mbggenerated
     */
    private BigDecimal weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_weight_log.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_weight_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_weight_log.id
     *
     * @return the value of ty_fish_weight_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_weight_log.id
     *
     * @param id the value for ty_fish_weight_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_weight_log.user_id
     *
     * @return the value of ty_fish_weight_log.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_weight_log.user_id
     *
     * @param userId the value for ty_fish_weight_log.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_weight_log.fish_id
     *
     * @return the value of ty_fish_weight_log.fish_id
     *
     * @mbggenerated
     */
    public String getFishId() {
        return fishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_weight_log.fish_id
     *
     * @param fishId the value for ty_fish_weight_log.fish_id
     *
     * @mbggenerated
     */
    public void setFishId(String fishId) {
        this.fishId = fishId == null ? null : fishId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_weight_log.grade
     *
     * @return the value of ty_fish_weight_log.grade
     *
     * @mbggenerated
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_weight_log.grade
     *
     * @param grade the value for ty_fish_weight_log.grade
     *
     * @mbggenerated
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_weight_log.rare
     *
     * @return the value of ty_fish_weight_log.rare
     *
     * @mbggenerated
     */
    public Integer getRare() {
        return rare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_weight_log.rare
     *
     * @param rare the value for ty_fish_weight_log.rare
     *
     * @mbggenerated
     */
    public void setRare(Integer rare) {
        this.rare = rare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_weight_log.weight
     *
     * @return the value of ty_fish_weight_log.weight
     *
     * @mbggenerated
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_weight_log.weight
     *
     * @param weight the value for ty_fish_weight_log.weight
     *
     * @mbggenerated
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_weight_log.update_time
     *
     * @return the value of ty_fish_weight_log.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_weight_log.update_time
     *
     * @param updateTime the value for ty_fish_weight_log.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_weight_log.create_time
     *
     * @return the value of ty_fish_weight_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_weight_log.create_time
     *
     * @param createTime the value for ty_fish_weight_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}