package com.toyo.fish.data.wrapper.zone.domain;

public class FishEquipmentLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_equipment_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_equipment_log.weight_log_id
     *
     * @mbggenerated
     */
    private Long weightLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_equipment_log.user_level
     *
     * @mbggenerated
     */
    private Integer userLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_equipment_log.rod_id
     *
     * @mbggenerated
     */
    private String rodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_equipment_log.rod_props
     *
     * @mbggenerated
     */
    private String rodProps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_equipment_log.wheel_id
     *
     * @mbggenerated
     */
    private String wheelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_equipment_log.wheel_props
     *
     * @mbggenerated
     */
    private String wheelProps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_equipment_log.line_id
     *
     * @mbggenerated
     */
    private String lineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_equipment_log.lure_id
     *
     * @mbggenerated
     */
    private String lureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_equipment_log.drug_id1
     *
     * @mbggenerated
     */
    private String drugId1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_equipment_log.drug_id2
     *
     * @mbggenerated
     */
    private String drugId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_equipment_log.big_fish_addition
     *
     * @mbggenerated
     */
    private String bigFishAddition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_equipment_log.tesion_triggers
     *
     * @mbggenerated
     */
    private Integer tesionTriggers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_equipment_log.tesion_used
     *
     * @mbggenerated
     */
    private Integer tesionUsed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_equipment_log.drag_triggers
     *
     * @mbggenerated
     */
    private Integer dragTriggers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_equipment_log.drag_used
     *
     * @mbggenerated
     */
    private Integer dragUsed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_equipment_log.fish_duration
     *
     * @mbggenerated
     */
    private Integer fishDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_fish_equipment_log.drug_id3
     *
     * @mbggenerated
     */
    private String drugId3;
    
    
    private Long weightFailedLogId;

    public Long getWeightFailedLogId() {
		return weightFailedLogId;
	}

	public void setWeightFailedLogId(Long weightFailedLogId) {
		this.weightFailedLogId = weightFailedLogId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_equipment_log.id
     *
     * @return the value of ty_fish_equipment_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_equipment_log.id
     *
     * @param id the value for ty_fish_equipment_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_equipment_log.weight_log_id
     *
     * @return the value of ty_fish_equipment_log.weight_log_id
     *
     * @mbggenerated
     */
    public Long getWeightLogId() {
        return weightLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_equipment_log.weight_log_id
     *
     * @param weightLogId the value for ty_fish_equipment_log.weight_log_id
     *
     * @mbggenerated
     */
    public void setWeightLogId(Long weightLogId) {
        this.weightLogId = weightLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_equipment_log.user_level
     *
     * @return the value of ty_fish_equipment_log.user_level
     *
     * @mbggenerated
     */
    public Integer getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_equipment_log.user_level
     *
     * @param userLevel the value for ty_fish_equipment_log.user_level
     *
     * @mbggenerated
     */
    public void setUserLevel(Integer userLevel) {
        this.userLevel = userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_equipment_log.rod_id
     *
     * @return the value of ty_fish_equipment_log.rod_id
     *
     * @mbggenerated
     */
    public String getRodId() {
        return rodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_equipment_log.rod_id
     *
     * @param rodId the value for ty_fish_equipment_log.rod_id
     *
     * @mbggenerated
     */
    public void setRodId(String rodId) {
        this.rodId = rodId == null ? null : rodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_equipment_log.rod_props
     *
     * @return the value of ty_fish_equipment_log.rod_props
     *
     * @mbggenerated
     */
    public String getRodProps() {
        return rodProps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_equipment_log.rod_props
     *
     * @param rodProps the value for ty_fish_equipment_log.rod_props
     *
     * @mbggenerated
     */
    public void setRodProps(String rodProps) {
        this.rodProps = rodProps == null ? null : rodProps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_equipment_log.wheel_id
     *
     * @return the value of ty_fish_equipment_log.wheel_id
     *
     * @mbggenerated
     */
    public String getWheelId() {
        return wheelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_equipment_log.wheel_id
     *
     * @param wheelId the value for ty_fish_equipment_log.wheel_id
     *
     * @mbggenerated
     */
    public void setWheelId(String wheelId) {
        this.wheelId = wheelId == null ? null : wheelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_equipment_log.wheel_props
     *
     * @return the value of ty_fish_equipment_log.wheel_props
     *
     * @mbggenerated
     */
    public String getWheelProps() {
        return wheelProps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_equipment_log.wheel_props
     *
     * @param wheelProps the value for ty_fish_equipment_log.wheel_props
     *
     * @mbggenerated
     */
    public void setWheelProps(String wheelProps) {
        this.wheelProps = wheelProps == null ? null : wheelProps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_equipment_log.line_id
     *
     * @return the value of ty_fish_equipment_log.line_id
     *
     * @mbggenerated
     */
    public String getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_equipment_log.line_id
     *
     * @param lineId the value for ty_fish_equipment_log.line_id
     *
     * @mbggenerated
     */
    public void setLineId(String lineId) {
        this.lineId = lineId == null ? null : lineId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_equipment_log.lure_id
     *
     * @return the value of ty_fish_equipment_log.lure_id
     *
     * @mbggenerated
     */
    public String getLureId() {
        return lureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_equipment_log.lure_id
     *
     * @param lureId the value for ty_fish_equipment_log.lure_id
     *
     * @mbggenerated
     */
    public void setLureId(String lureId) {
        this.lureId = lureId == null ? null : lureId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_equipment_log.drug_id1
     *
     * @return the value of ty_fish_equipment_log.drug_id1
     *
     * @mbggenerated
     */
    public String getDrugId1() {
        return drugId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_equipment_log.drug_id1
     *
     * @param drugId1 the value for ty_fish_equipment_log.drug_id1
     *
     * @mbggenerated
     */
    public void setDrugId1(String drugId1) {
        this.drugId1 = drugId1 == null ? null : drugId1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_equipment_log.drug_id2
     *
     * @return the value of ty_fish_equipment_log.drug_id2
     *
     * @mbggenerated
     */
    public String getDrugId2() {
        return drugId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_equipment_log.drug_id2
     *
     * @param drugId2 the value for ty_fish_equipment_log.drug_id2
     *
     * @mbggenerated
     */
    public void setDrugId2(String drugId2) {
        this.drugId2 = drugId2 == null ? null : drugId2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_equipment_log.big_fish_addition
     *
     * @return the value of ty_fish_equipment_log.big_fish_addition
     *
     * @mbggenerated
     */
    public String getBigFishAddition() {
        return bigFishAddition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_equipment_log.big_fish_addition
     *
     * @param bigFishAddition the value for ty_fish_equipment_log.big_fish_addition
     *
     * @mbggenerated
     */
    public void setBigFishAddition(String bigFishAddition) {
        this.bigFishAddition = bigFishAddition == null ? null : bigFishAddition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_equipment_log.tesion_triggers
     *
     * @return the value of ty_fish_equipment_log.tesion_triggers
     *
     * @mbggenerated
     */
    public Integer getTesionTriggers() {
        return tesionTriggers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_equipment_log.tesion_triggers
     *
     * @param tesionTriggers the value for ty_fish_equipment_log.tesion_triggers
     *
     * @mbggenerated
     */
    public void setTesionTriggers(Integer tesionTriggers) {
        this.tesionTriggers = tesionTriggers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_equipment_log.tesion_used
     *
     * @return the value of ty_fish_equipment_log.tesion_used
     *
     * @mbggenerated
     */
    public Integer getTesionUsed() {
        return tesionUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_equipment_log.tesion_used
     *
     * @param tesionUsed the value for ty_fish_equipment_log.tesion_used
     *
     * @mbggenerated
     */
    public void setTesionUsed(Integer tesionUsed) {
        this.tesionUsed = tesionUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_equipment_log.drag_triggers
     *
     * @return the value of ty_fish_equipment_log.drag_triggers
     *
     * @mbggenerated
     */
    public Integer getDragTriggers() {
        return dragTriggers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_equipment_log.drag_triggers
     *
     * @param dragTriggers the value for ty_fish_equipment_log.drag_triggers
     *
     * @mbggenerated
     */
    public void setDragTriggers(Integer dragTriggers) {
        this.dragTriggers = dragTriggers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_equipment_log.drag_used
     *
     * @return the value of ty_fish_equipment_log.drag_used
     *
     * @mbggenerated
     */
    public Integer getDragUsed() {
        return dragUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_equipment_log.drag_used
     *
     * @param dragUsed the value for ty_fish_equipment_log.drag_used
     *
     * @mbggenerated
     */
    public void setDragUsed(Integer dragUsed) {
        this.dragUsed = dragUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_equipment_log.fish_duration
     *
     * @return the value of ty_fish_equipment_log.fish_duration
     *
     * @mbggenerated
     */
    public Integer getFishDuration() {
        return fishDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_equipment_log.fish_duration
     *
     * @param fishDuration the value for ty_fish_equipment_log.fish_duration
     *
     * @mbggenerated
     */
    public void setFishDuration(Integer fishDuration) {
        this.fishDuration = fishDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_fish_equipment_log.drug_id3
     *
     * @return the value of ty_fish_equipment_log.drug_id3
     *
     * @mbggenerated
     */
    public String getDrugId3() {
        return drugId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_fish_equipment_log.drug_id3
     *
     * @param drugId3 the value for ty_fish_equipment_log.drug_id3
     *
     * @mbggenerated
     */
    public void setDrugId3(String drugId3) {
        this.drugId3 = drugId3 == null ? null : drugId3.trim();
    }
}