package com.toyo.fish.data.wrapper.zone.domain;

public class GuideLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_guide_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_guide_log.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_guide_log.guide_date
     *
     * @mbggenerated
     */
    private String guideDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_guide_log.id
     *
     * @return the value of ty_guide_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_guide_log.id
     *
     * @param id the value for ty_guide_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_guide_log.user_id
     *
     * @return the value of ty_guide_log.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_guide_log.user_id
     *
     * @param userId the value for ty_guide_log.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_guide_log.guide_date
     *
     * @return the value of ty_guide_log.guide_date
     *
     * @mbggenerated
     */
    public String getGuideDate() {
        return guideDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_guide_log.guide_date
     *
     * @param guideDate the value for ty_guide_log.guide_date
     *
     * @mbggenerated
     */
    public void setGuideDate(String guideDate) {
        this.guideDate = guideDate == null ? null : guideDate.trim();
    }
}