package com.toyo.fish.data.wrapper.zone.domain;

import java.util.Date;

public class VitLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_vit_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_vit_log.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_vit_log.vit
     *
     * @mbggenerated
     */
    private Integer vit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_vit_log.online
     *
     * @mbggenerated
     */
    private Integer online;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_vit_log.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_vit_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;
    
    private Long clientId;
    

    public Long getClientId() {
		return clientId;
	}

	public void setClientId(Long clientId) {
		this.clientId = clientId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_vit_log.id
     *
     * @return the value of ty_vit_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_vit_log.id
     *
     * @param id the value for ty_vit_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_vit_log.user_id
     *
     * @return the value of ty_vit_log.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_vit_log.user_id
     *
     * @param userId the value for ty_vit_log.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_vit_log.vit
     *
     * @return the value of ty_vit_log.vit
     *
     * @mbggenerated
     */
    public Integer getVit() {
        return vit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_vit_log.vit
     *
     * @param vit the value for ty_vit_log.vit
     *
     * @mbggenerated
     */
    public void setVit(Integer vit) {
        this.vit = vit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_vit_log.online
     *
     * @return the value of ty_vit_log.online
     *
     * @mbggenerated
     */
    public Integer getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_vit_log.online
     *
     * @param online the value for ty_vit_log.online
     *
     * @mbggenerated
     */
    public void setOnline(Integer online) {
        this.online = online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_vit_log.update_time
     *
     * @return the value of ty_vit_log.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_vit_log.update_time
     *
     * @param updateTime the value for ty_vit_log.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_vit_log.create_time
     *
     * @return the value of ty_vit_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_vit_log.create_time
     *
     * @param createTime the value for ty_vit_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}