package com.toyo.fish.data.wrapper.domain;

import java.util.Date;

public class ApkVersionUpdateLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_apk_version_update_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_apk_version_update_log.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_apk_version_update_log.apk_version
     *
     * @mbggenerated
     */
    private String apkVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_apk_version_update_log.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_apk_version_update_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_apk_version_update_log.id
     *
     * @return the value of ty_apk_version_update_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_apk_version_update_log.id
     *
     * @param id the value for ty_apk_version_update_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_apk_version_update_log.user_id
     *
     * @return the value of ty_apk_version_update_log.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_apk_version_update_log.user_id
     *
     * @param userId the value for ty_apk_version_update_log.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_apk_version_update_log.apk_version
     *
     * @return the value of ty_apk_version_update_log.apk_version
     *
     * @mbggenerated
     */
    public String getApkVersion() {
        return apkVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_apk_version_update_log.apk_version
     *
     * @param apkVersion the value for ty_apk_version_update_log.apk_version
     *
     * @mbggenerated
     */
    public void setApkVersion(String apkVersion) {
        this.apkVersion = apkVersion == null ? null : apkVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_apk_version_update_log.update_time
     *
     * @return the value of ty_apk_version_update_log.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_apk_version_update_log.update_time
     *
     * @param updateTime the value for ty_apk_version_update_log.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_apk_version_update_log.create_time
     *
     * @return the value of ty_apk_version_update_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_apk_version_update_log.create_time
     *
     * @param createTime the value for ty_apk_version_update_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}