package com.toyo.fish.data.wrapper.domain;

import java.util.Date;

public class Login {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_login.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_login.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_login.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_login.device_id
     *
     * @mbggenerated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_login.connection_id
     *
     * @mbggenerated
     */
    private String connectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_login.des_key
     *
     * @mbggenerated
     */
    private String desKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_login.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_login.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_login.id
     *
     * @return the value of ty_login.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_login.id
     *
     * @param id the value for ty_login.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_login.user_id
     *
     * @return the value of ty_login.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_login.user_id
     *
     * @param userId the value for ty_login.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_login.token
     *
     * @return the value of ty_login.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_login.token
     *
     * @param token the value for ty_login.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_login.device_id
     *
     * @return the value of ty_login.device_id
     *
     * @mbggenerated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_login.device_id
     *
     * @param deviceId the value for ty_login.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_login.connection_id
     *
     * @return the value of ty_login.connection_id
     *
     * @mbggenerated
     */
  
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_login.des_key
     *
     * @return the value of ty_login.des_key
     *
     * @mbggenerated
     */
    public String getDesKey() {
        return desKey;
    }

    public String getConnectionId() {
		return connectionId;
	}

	public void setConnectionId(String connectionId) {
		this.connectionId = connectionId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_login.des_key
     *
     * @param desKey the value for ty_login.des_key
     *
     * @mbggenerated
     */
    public void setDesKey(String desKey) {
        this.desKey = desKey == null ? null : desKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_login.create_time
     *
     * @return the value of ty_login.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_login.create_time
     *
     * @param createTime the value for ty_login.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_login.update_time
     *
     * @return the value of ty_login.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_login.update_time
     *
     * @param updateTime the value for ty_login.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}