package com.toyo.fish.data.wrapper.domain;

import java.util.Date;

public class ProtocolHandler implements java.io.Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -956794073599025847L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_protocol_handler.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_protocol_handler.handle
     *
     * @mbggenerated
     */
    private String handle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_protocol_handler.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_protocol_handler.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_protocol_handler.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_protocol_handler.id
     *
     * @return the value of ty_protocol_handler.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_protocol_handler.id
     *
     * @param id the value for ty_protocol_handler.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_protocol_handler.handle
     *
     * @return the value of ty_protocol_handler.handle
     *
     * @mbggenerated
     */
    public String getHandle() {
        return handle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_protocol_handler.handle
     *
     * @param handle the value for ty_protocol_handler.handle
     *
     * @mbggenerated
     */
    public void setHandle(String handle) {
        this.handle = handle == null ? null : handle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_protocol_handler.state
     *
     * @return the value of ty_protocol_handler.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_protocol_handler.state
     *
     * @param state the value for ty_protocol_handler.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_protocol_handler.update_time
     *
     * @return the value of ty_protocol_handler.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_protocol_handler.update_time
     *
     * @param updateTime the value for ty_protocol_handler.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_protocol_handler.create_time
     *
     * @return the value of ty_protocol_handler.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_protocol_handler.create_time
     *
     * @param createTime the value for ty_protocol_handler.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}