package com.toyo.fish.data.wrapper.domain;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;

public class UserAccountFriends implements Serializable {
    /**
	 * 
	 */
	private static final long MAX_MAIL_CHECK_INTERVAL=3*1000;
	private static final long serialVersionUID = -8021971690111553427L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_user_account.id
     *
     * @mbggenerated
     */
    private Long id;

   


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_user_account.channel_id
     *
     * @mbggenerated
     */
    private Integer channelId;

   
   
    
    private String avatar;
    private String nickName;
    
    private String apkVersion;
    
    private Integer level;
    @JsonIgnore
    private int state;
    @JsonIgnore
    private long lastMailChecked;
    
    
    public boolean shouldCheck(){
    	return System.currentTimeMillis()-lastMailChecked>MAX_MAIL_CHECK_INTERVAL;
    }

    public long getLastMailChecked() {
		return lastMailChecked;
	}

	public void setLastMailChecked(long lastMailChecked) {
		this.lastMailChecked = lastMailChecked;
	}

	public int getState() {
		return state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public Integer getLevel() {
		return level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public String getApkVersion() {
		return apkVersion;
	}

	public void setApkVersion(String apkVersion) {
		this.apkVersion = apkVersion;
	}

	public String getNickName() {
		return nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getAvatar() {
		return avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_user_account.id
     *
     * @return the value of ty_user_account.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_user_account.id
     *
     * @param id the value for ty_user_account.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

   
}