package com.toyo.fish.data.wrapper.domain;

import java.util.Date;

public class ValidCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_valid_code.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_valid_code.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_valid_code.valid_code
     *
     * @mbggenerated
     */
    private String validCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_valid_code.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_valid_code.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_valid_code.id
     *
     * @return the value of ty_valid_code.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_valid_code.id
     *
     * @param id the value for ty_valid_code.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_valid_code.user_id
     *
     * @return the value of ty_valid_code.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_valid_code.user_id
     *
     * @param userId the value for ty_valid_code.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_valid_code.valid_code
     *
     * @return the value of ty_valid_code.valid_code
     *
     * @mbggenerated
     */
    public String getValidCode() {
        return validCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_valid_code.valid_code
     *
     * @param validCode the value for ty_valid_code.valid_code
     *
     * @mbggenerated
     */
    public void setValidCode(String validCode) {
        this.validCode = validCode == null ? null : validCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_valid_code.create_time
     *
     * @return the value of ty_valid_code.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_valid_code.create_time
     *
     * @param createTime the value for ty_valid_code.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_valid_code.update_time
     *
     * @return the value of ty_valid_code.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_valid_code.update_time
     *
     * @param updateTime the value for ty_valid_code.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}