package com.sky.mobile.protocol.domain;

import java.util.Date;

public class AnZhiNotify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_anzhi_notify.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_anzhi_notify.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_anzhi_notify.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_anzhi_notify.order_time
     *
     * @mbggenerated
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_anzhi_notify.order_account
     *
     * @mbggenerated
     */
    private String orderAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_anzhi_notify.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_anzhi_notify.msg
     *
     * @mbggenerated
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_anzhi_notify.local_order_id
     *
     * @mbggenerated
     */
    private String localOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_anzhi_notify.notify_time
     *
     * @mbggenerated
     */
    private Date notifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_anzhi_notify.red_bag_money
     *
     * @mbggenerated
     */
    private Integer redBagMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_anzhi_notify.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_anzhi_notify.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_anzhi_notify.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_anzhi_notify.id
     *
     * @return the value of tbl_anzhi_notify.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_anzhi_notify.id
     *
     * @param id the value for tbl_anzhi_notify.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_anzhi_notify.uid
     *
     * @return the value of tbl_anzhi_notify.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_anzhi_notify.uid
     *
     * @param uid the value for tbl_anzhi_notify.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_anzhi_notify.order_id
     *
     * @return the value of tbl_anzhi_notify.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_anzhi_notify.order_id
     *
     * @param orderId the value for tbl_anzhi_notify.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_anzhi_notify.order_time
     *
     * @return the value of tbl_anzhi_notify.order_time
     *
     * @mbggenerated
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_anzhi_notify.order_time
     *
     * @param orderTime the value for tbl_anzhi_notify.order_time
     *
     * @mbggenerated
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_anzhi_notify.order_account
     *
     * @return the value of tbl_anzhi_notify.order_account
     *
     * @mbggenerated
     */
    public String getOrderAccount() {
        return orderAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_anzhi_notify.order_account
     *
     * @param orderAccount the value for tbl_anzhi_notify.order_account
     *
     * @mbggenerated
     */
    public void setOrderAccount(String orderAccount) {
        this.orderAccount = orderAccount == null ? null : orderAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_anzhi_notify.state
     *
     * @return the value of tbl_anzhi_notify.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_anzhi_notify.state
     *
     * @param state the value for tbl_anzhi_notify.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_anzhi_notify.msg
     *
     * @return the value of tbl_anzhi_notify.msg
     *
     * @mbggenerated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_anzhi_notify.msg
     *
     * @param msg the value for tbl_anzhi_notify.msg
     *
     * @mbggenerated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_anzhi_notify.local_order_id
     *
     * @return the value of tbl_anzhi_notify.local_order_id
     *
     * @mbggenerated
     */
    public String getLocalOrderId() {
        return localOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_anzhi_notify.local_order_id
     *
     * @param localOrderId the value for tbl_anzhi_notify.local_order_id
     *
     * @mbggenerated
     */
    public void setLocalOrderId(String localOrderId) {
        this.localOrderId = localOrderId == null ? null : localOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_anzhi_notify.notify_time
     *
     * @return the value of tbl_anzhi_notify.notify_time
     *
     * @mbggenerated
     */
    public Date getNotifyTime() {
        return notifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_anzhi_notify.notify_time
     *
     * @param notifyTime the value for tbl_anzhi_notify.notify_time
     *
     * @mbggenerated
     */
    public void setNotifyTime(Date notifyTime) {
        this.notifyTime = notifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_anzhi_notify.red_bag_money
     *
     * @return the value of tbl_anzhi_notify.red_bag_money
     *
     * @mbggenerated
     */
    public Integer getRedBagMoney() {
        return redBagMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_anzhi_notify.red_bag_money
     *
     * @param redBagMoney the value for tbl_anzhi_notify.red_bag_money
     *
     * @mbggenerated
     */
    public void setRedBagMoney(Integer redBagMoney) {
        this.redBagMoney = redBagMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_anzhi_notify.memo
     *
     * @return the value of tbl_anzhi_notify.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_anzhi_notify.memo
     *
     * @param memo the value for tbl_anzhi_notify.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_anzhi_notify.create_time
     *
     * @return the value of tbl_anzhi_notify.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_anzhi_notify.create_time
     *
     * @param createTime the value for tbl_anzhi_notify.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_anzhi_notify.update_time
     *
     * @return the value of tbl_anzhi_notify.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_anzhi_notify.update_time
     *
     * @param updateTime the value for tbl_anzhi_notify.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}