package com.sky.mobile.protocol.domain;

import java.util.Date;

public class BaiduNotify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_baidu_notify.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_baidu_notify.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_baidu_notify.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_baidu_notify.amount
     *
     * @mbggenerated
     */
    private String amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_baidu_notify.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_baidu_notify.jfd
     *
     * @mbggenerated
     */
    private String jfd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_baidu_notify.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_baidu_notify.pay_name
     *
     * @mbggenerated
     */
    private String payName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_baidu_notify.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_baidu_notify.channel
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_baidu_notify.orign
     *
     * @mbggenerated
     */
    private String orign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_baidu_notify.sign
     *
     * @mbggenerated
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_baidu_notify.ext_channel
     *
     * @mbggenerated
     */
    private String extChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_baidu_notify.cp_define_part
     *
     * @mbggenerated
     */
    private String cpDefinePart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_baidu_notify.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_baidu_notify.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_baidu_notify.id
     *
     * @return the value of tbl_baidu_notify.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_baidu_notify.id
     *
     * @param id the value for tbl_baidu_notify.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_baidu_notify.app_id
     *
     * @return the value of tbl_baidu_notify.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_baidu_notify.app_id
     *
     * @param appId the value for tbl_baidu_notify.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_baidu_notify.order_id
     *
     * @return the value of tbl_baidu_notify.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_baidu_notify.order_id
     *
     * @param orderId the value for tbl_baidu_notify.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_baidu_notify.amount
     *
     * @return the value of tbl_baidu_notify.amount
     *
     * @mbggenerated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_baidu_notify.amount
     *
     * @param amount the value for tbl_baidu_notify.amount
     *
     * @mbggenerated
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_baidu_notify.unit
     *
     * @return the value of tbl_baidu_notify.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_baidu_notify.unit
     *
     * @param unit the value for tbl_baidu_notify.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_baidu_notify.jfd
     *
     * @return the value of tbl_baidu_notify.jfd
     *
     * @mbggenerated
     */
    public String getJfd() {
        return jfd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_baidu_notify.jfd
     *
     * @param jfd the value for tbl_baidu_notify.jfd
     *
     * @mbggenerated
     */
    public void setJfd(String jfd) {
        this.jfd = jfd == null ? null : jfd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_baidu_notify.status
     *
     * @return the value of tbl_baidu_notify.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_baidu_notify.status
     *
     * @param status the value for tbl_baidu_notify.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_baidu_notify.pay_name
     *
     * @return the value of tbl_baidu_notify.pay_name
     *
     * @mbggenerated
     */
    public String getPayName() {
        return payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_baidu_notify.pay_name
     *
     * @param payName the value for tbl_baidu_notify.pay_name
     *
     * @mbggenerated
     */
    public void setPayName(String payName) {
        this.payName = payName == null ? null : payName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_baidu_notify.phone
     *
     * @return the value of tbl_baidu_notify.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_baidu_notify.phone
     *
     * @param phone the value for tbl_baidu_notify.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_baidu_notify.channel
     *
     * @return the value of tbl_baidu_notify.channel
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_baidu_notify.channel
     *
     * @param channel the value for tbl_baidu_notify.channel
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_baidu_notify.orign
     *
     * @return the value of tbl_baidu_notify.orign
     *
     * @mbggenerated
     */
    public String getOrign() {
        return orign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_baidu_notify.orign
     *
     * @param orign the value for tbl_baidu_notify.orign
     *
     * @mbggenerated
     */
    public void setOrign(String orign) {
        this.orign = orign == null ? null : orign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_baidu_notify.sign
     *
     * @return the value of tbl_baidu_notify.sign
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_baidu_notify.sign
     *
     * @param sign the value for tbl_baidu_notify.sign
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_baidu_notify.ext_channel
     *
     * @return the value of tbl_baidu_notify.ext_channel
     *
     * @mbggenerated
     */
    public String getExtChannel() {
        return extChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_baidu_notify.ext_channel
     *
     * @param extChannel the value for tbl_baidu_notify.ext_channel
     *
     * @mbggenerated
     */
    public void setExtChannel(String extChannel) {
        this.extChannel = extChannel == null ? null : extChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_baidu_notify.cp_define_part
     *
     * @return the value of tbl_baidu_notify.cp_define_part
     *
     * @mbggenerated
     */
    public String getCpDefinePart() {
        return cpDefinePart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_baidu_notify.cp_define_part
     *
     * @param cpDefinePart the value for tbl_baidu_notify.cp_define_part
     *
     * @mbggenerated
     */
    public void setCpDefinePart(String cpDefinePart) {
        this.cpDefinePart = cpDefinePart == null ? null : cpDefinePart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_baidu_notify.create_time
     *
     * @return the value of tbl_baidu_notify.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_baidu_notify.create_time
     *
     * @param createTime the value for tbl_baidu_notify.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_baidu_notify.update_time
     *
     * @return the value of tbl_baidu_notify.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_baidu_notify.update_time
     *
     * @param updateTime the value for tbl_baidu_notify.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}