package com.sky.mobile.protocol.domain;

import java.util.Date;

public class HuaweiNotify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_huawei_notify.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_huawei_notify.msg
     *
     * @mbggenerated
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_huawei_notify.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_huawei_notify.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_huawei_notify.pay_type
     *
     * @mbggenerated
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_huawei_notify.amount
     *
     * @mbggenerated
     */
    private String amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_huawei_notify.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_huawei_notify.notify_time
     *
     * @mbggenerated
     */
    private String notifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_huawei_notify.request_id
     *
     * @mbggenerated
     */
    private String requestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_huawei_notify.bank_id
     *
     * @mbggenerated
     */
    private String bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_huawei_notify.trade_time
     *
     * @mbggenerated
     */
    private String tradeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_huawei_notify.access_mode
     *
     * @mbggenerated
     */
    private String accessMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_huawei_notify.spending
     *
     * @mbggenerated
     */
    private String spending;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_huawei_notify.ext_reserved
     *
     * @mbggenerated
     */
    private String extReserved;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_huawei_notify.sys_reserved
     *
     * @mbggenerated
     */
    private String sysReserved;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_huawei_notify.sign_type
     *
     * @mbggenerated
     */
    private String signType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_huawei_notify.sign
     *
     * @mbggenerated
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_huawei_notify.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_huawei_notify.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_huawei_notify.id
     *
     * @return the value of tbl_huawei_notify.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_huawei_notify.id
     *
     * @param id the value for tbl_huawei_notify.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_huawei_notify.msg
     *
     * @return the value of tbl_huawei_notify.msg
     *
     * @mbggenerated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_huawei_notify.msg
     *
     * @param msg the value for tbl_huawei_notify.msg
     *
     * @mbggenerated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_huawei_notify.user_name
     *
     * @return the value of tbl_huawei_notify.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_huawei_notify.user_name
     *
     * @param userName the value for tbl_huawei_notify.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_huawei_notify.product_name
     *
     * @return the value of tbl_huawei_notify.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_huawei_notify.product_name
     *
     * @param productName the value for tbl_huawei_notify.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_huawei_notify.pay_type
     *
     * @return the value of tbl_huawei_notify.pay_type
     *
     * @mbggenerated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_huawei_notify.pay_type
     *
     * @param payType the value for tbl_huawei_notify.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_huawei_notify.amount
     *
     * @return the value of tbl_huawei_notify.amount
     *
     * @mbggenerated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_huawei_notify.amount
     *
     * @param amount the value for tbl_huawei_notify.amount
     *
     * @mbggenerated
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_huawei_notify.order_id
     *
     * @return the value of tbl_huawei_notify.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_huawei_notify.order_id
     *
     * @param orderId the value for tbl_huawei_notify.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_huawei_notify.notify_time
     *
     * @return the value of tbl_huawei_notify.notify_time
     *
     * @mbggenerated
     */
    public String getNotifyTime() {
        return notifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_huawei_notify.notify_time
     *
     * @param notifyTime the value for tbl_huawei_notify.notify_time
     *
     * @mbggenerated
     */
    public void setNotifyTime(String notifyTime) {
        this.notifyTime = notifyTime == null ? null : notifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_huawei_notify.request_id
     *
     * @return the value of tbl_huawei_notify.request_id
     *
     * @mbggenerated
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_huawei_notify.request_id
     *
     * @param requestId the value for tbl_huawei_notify.request_id
     *
     * @mbggenerated
     */
    public void setRequestId(String requestId) {
        this.requestId = requestId == null ? null : requestId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_huawei_notify.bank_id
     *
     * @return the value of tbl_huawei_notify.bank_id
     *
     * @mbggenerated
     */
    public String getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_huawei_notify.bank_id
     *
     * @param bankId the value for tbl_huawei_notify.bank_id
     *
     * @mbggenerated
     */
    public void setBankId(String bankId) {
        this.bankId = bankId == null ? null : bankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_huawei_notify.trade_time
     *
     * @return the value of tbl_huawei_notify.trade_time
     *
     * @mbggenerated
     */
    public String getTradeTime() {
        return tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_huawei_notify.trade_time
     *
     * @param tradeTime the value for tbl_huawei_notify.trade_time
     *
     * @mbggenerated
     */
    public void setTradeTime(String tradeTime) {
        this.tradeTime = tradeTime == null ? null : tradeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_huawei_notify.access_mode
     *
     * @return the value of tbl_huawei_notify.access_mode
     *
     * @mbggenerated
     */
    public String getAccessMode() {
        return accessMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_huawei_notify.access_mode
     *
     * @param accessMode the value for tbl_huawei_notify.access_mode
     *
     * @mbggenerated
     */
    public void setAccessMode(String accessMode) {
        this.accessMode = accessMode == null ? null : accessMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_huawei_notify.spending
     *
     * @return the value of tbl_huawei_notify.spending
     *
     * @mbggenerated
     */
    public String getSpending() {
        return spending;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_huawei_notify.spending
     *
     * @param spending the value for tbl_huawei_notify.spending
     *
     * @mbggenerated
     */
    public void setSpending(String spending) {
        this.spending = spending == null ? null : spending.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_huawei_notify.ext_reserved
     *
     * @return the value of tbl_huawei_notify.ext_reserved
     *
     * @mbggenerated
     */
    public String getExtReserved() {
        return extReserved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_huawei_notify.ext_reserved
     *
     * @param extReserved the value for tbl_huawei_notify.ext_reserved
     *
     * @mbggenerated
     */
    public void setExtReserved(String extReserved) {
        this.extReserved = extReserved == null ? null : extReserved.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_huawei_notify.sys_reserved
     *
     * @return the value of tbl_huawei_notify.sys_reserved
     *
     * @mbggenerated
     */
    public String getSysReserved() {
        return sysReserved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_huawei_notify.sys_reserved
     *
     * @param sysReserved the value for tbl_huawei_notify.sys_reserved
     *
     * @mbggenerated
     */
    public void setSysReserved(String sysReserved) {
        this.sysReserved = sysReserved == null ? null : sysReserved.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_huawei_notify.sign_type
     *
     * @return the value of tbl_huawei_notify.sign_type
     *
     * @mbggenerated
     */
    public String getSignType() {
        return signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_huawei_notify.sign_type
     *
     * @param signType the value for tbl_huawei_notify.sign_type
     *
     * @mbggenerated
     */
    public void setSignType(String signType) {
        this.signType = signType == null ? null : signType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_huawei_notify.sign
     *
     * @return the value of tbl_huawei_notify.sign
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_huawei_notify.sign
     *
     * @param sign the value for tbl_huawei_notify.sign
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_huawei_notify.create_time
     *
     * @return the value of tbl_huawei_notify.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_huawei_notify.create_time
     *
     * @param createTime the value for tbl_huawei_notify.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_huawei_notify.update_time
     *
     * @return the value of tbl_huawei_notify.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_huawei_notify.update_time
     *
     * @param updateTime the value for tbl_huawei_notify.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}