package com.sky.mobile.protocol.domain;

import java.util.Date;

public class JinliNotify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_jinli_notify.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_jinli_notify.api_key
     *
     * @mbggenerated
     */
    private String apiKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_jinli_notify.close_time
     *
     * @mbggenerated
     */
    private String closeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_jinli_notify.jinli_create_time
     *
     * @mbggenerated
     */
    private String jinliCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_jinli_notify.deal_price
     *
     * @mbggenerated
     */
    private String dealPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_jinli_notify.out_order_no
     *
     * @mbggenerated
     */
    private String outOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_jinli_notify.pay_channel
     *
     * @mbggenerated
     */
    private String payChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_jinli_notify.submit_time
     *
     * @mbggenerated
     */
    private String submitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_jinli_notify.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_jinli_notify.sign
     *
     * @mbggenerated
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_jinli_notify.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_jinli_notify.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_jinli_notify.id
     *
     * @return the value of tbl_jinli_notify.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_jinli_notify.id
     *
     * @param id the value for tbl_jinli_notify.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_jinli_notify.api_key
     *
     * @return the value of tbl_jinli_notify.api_key
     *
     * @mbggenerated
     */
    public String getApiKey() {
        return apiKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_jinli_notify.api_key
     *
     * @param apiKey the value for tbl_jinli_notify.api_key
     *
     * @mbggenerated
     */
    public void setApiKey(String apiKey) {
        this.apiKey = apiKey == null ? null : apiKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_jinli_notify.close_time
     *
     * @return the value of tbl_jinli_notify.close_time
     *
     * @mbggenerated
     */
    public String getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_jinli_notify.close_time
     *
     * @param closeTime the value for tbl_jinli_notify.close_time
     *
     * @mbggenerated
     */
    public void setCloseTime(String closeTime) {
        this.closeTime = closeTime == null ? null : closeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_jinli_notify.jinli_create_time
     *
     * @return the value of tbl_jinli_notify.jinli_create_time
     *
     * @mbggenerated
     */
    public String getJinliCreateTime() {
        return jinliCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_jinli_notify.jinli_create_time
     *
     * @param jinliCreateTime the value for tbl_jinli_notify.jinli_create_time
     *
     * @mbggenerated
     */
    public void setJinliCreateTime(String jinliCreateTime) {
        this.jinliCreateTime = jinliCreateTime == null ? null : jinliCreateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_jinli_notify.deal_price
     *
     * @return the value of tbl_jinli_notify.deal_price
     *
     * @mbggenerated
     */
    public String getDealPrice() {
        return dealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_jinli_notify.deal_price
     *
     * @param dealPrice the value for tbl_jinli_notify.deal_price
     *
     * @mbggenerated
     */
    public void setDealPrice(String dealPrice) {
        this.dealPrice = dealPrice == null ? null : dealPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_jinli_notify.out_order_no
     *
     * @return the value of tbl_jinli_notify.out_order_no
     *
     * @mbggenerated
     */
    public String getOutOrderNo() {
        return outOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_jinli_notify.out_order_no
     *
     * @param outOrderNo the value for tbl_jinli_notify.out_order_no
     *
     * @mbggenerated
     */
    public void setOutOrderNo(String outOrderNo) {
        this.outOrderNo = outOrderNo == null ? null : outOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_jinli_notify.pay_channel
     *
     * @return the value of tbl_jinli_notify.pay_channel
     *
     * @mbggenerated
     */
    public String getPayChannel() {
        return payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_jinli_notify.pay_channel
     *
     * @param payChannel the value for tbl_jinli_notify.pay_channel
     *
     * @mbggenerated
     */
    public void setPayChannel(String payChannel) {
        this.payChannel = payChannel == null ? null : payChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_jinli_notify.submit_time
     *
     * @return the value of tbl_jinli_notify.submit_time
     *
     * @mbggenerated
     */
    public String getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_jinli_notify.submit_time
     *
     * @param submitTime the value for tbl_jinli_notify.submit_time
     *
     * @mbggenerated
     */
    public void setSubmitTime(String submitTime) {
        this.submitTime = submitTime == null ? null : submitTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_jinli_notify.user_id
     *
     * @return the value of tbl_jinli_notify.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_jinli_notify.user_id
     *
     * @param userId the value for tbl_jinli_notify.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_jinli_notify.sign
     *
     * @return the value of tbl_jinli_notify.sign
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_jinli_notify.sign
     *
     * @param sign the value for tbl_jinli_notify.sign
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_jinli_notify.create_time
     *
     * @return the value of tbl_jinli_notify.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_jinli_notify.create_time
     *
     * @param createTime the value for tbl_jinli_notify.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_jinli_notify.update_time
     *
     * @return the value of tbl_jinli_notify.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_jinli_notify.update_time
     *
     * @param updateTime the value for tbl_jinli_notify.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}