package com.sky.mobile.protocol.domain;

import java.util.Date;

public class KuPaiNotify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_kupai_notify.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_kupai_notify.amount
     *
     * @mbggenerated
     */
    private String amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_kupai_notify.extra
     *
     * @mbggenerated
     */
    private String extra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_kupai_notify.app_key
     *
     * @mbggenerated
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_kupai_notify.goods_key
     *
     * @mbggenerated
     */
    private String goodsKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_kupai_notify.trade_id
     *
     * @mbggenerated
     */
    private String tradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_kupai_notify.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_kupai_notify.op
     *
     * @mbggenerated
     */
    private String op;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_kupai_notify.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_kupai_notify.ts
     *
     * @mbggenerated
     */
    private String ts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_kupai_notify.ch_key
     *
     * @mbggenerated
     */
    private String chKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_kupai_notify.msg
     *
     * @mbggenerated
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_kupai_notify.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_kupai_notify.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_kupai_notify.id
     *
     * @return the value of tbl_kupai_notify.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_kupai_notify.id
     *
     * @param id the value for tbl_kupai_notify.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_kupai_notify.amount
     *
     * @return the value of tbl_kupai_notify.amount
     *
     * @mbggenerated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_kupai_notify.amount
     *
     * @param amount the value for tbl_kupai_notify.amount
     *
     * @mbggenerated
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_kupai_notify.extra
     *
     * @return the value of tbl_kupai_notify.extra
     *
     * @mbggenerated
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_kupai_notify.extra
     *
     * @param extra the value for tbl_kupai_notify.extra
     *
     * @mbggenerated
     */
    public void setExtra(String extra) {
        this.extra = extra == null ? null : extra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_kupai_notify.app_key
     *
     * @return the value of tbl_kupai_notify.app_key
     *
     * @mbggenerated
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_kupai_notify.app_key
     *
     * @param appKey the value for tbl_kupai_notify.app_key
     *
     * @mbggenerated
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_kupai_notify.goods_key
     *
     * @return the value of tbl_kupai_notify.goods_key
     *
     * @mbggenerated
     */
    public String getGoodsKey() {
        return goodsKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_kupai_notify.goods_key
     *
     * @param goodsKey the value for tbl_kupai_notify.goods_key
     *
     * @mbggenerated
     */
    public void setGoodsKey(String goodsKey) {
        this.goodsKey = goodsKey == null ? null : goodsKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_kupai_notify.trade_id
     *
     * @return the value of tbl_kupai_notify.trade_id
     *
     * @mbggenerated
     */
    public String getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_kupai_notify.trade_id
     *
     * @param tradeId the value for tbl_kupai_notify.trade_id
     *
     * @mbggenerated
     */
    public void setTradeId(String tradeId) {
        this.tradeId = tradeId == null ? null : tradeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_kupai_notify.uid
     *
     * @return the value of tbl_kupai_notify.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_kupai_notify.uid
     *
     * @param uid the value for tbl_kupai_notify.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_kupai_notify.op
     *
     * @return the value of tbl_kupai_notify.op
     *
     * @mbggenerated
     */
    public String getOp() {
        return op;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_kupai_notify.op
     *
     * @param op the value for tbl_kupai_notify.op
     *
     * @mbggenerated
     */
    public void setOp(String op) {
        this.op = op == null ? null : op.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_kupai_notify.area
     *
     * @return the value of tbl_kupai_notify.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_kupai_notify.area
     *
     * @param area the value for tbl_kupai_notify.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_kupai_notify.ts
     *
     * @return the value of tbl_kupai_notify.ts
     *
     * @mbggenerated
     */
    public String getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_kupai_notify.ts
     *
     * @param ts the value for tbl_kupai_notify.ts
     *
     * @mbggenerated
     */
    public void setTs(String ts) {
        this.ts = ts == null ? null : ts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_kupai_notify.ch_key
     *
     * @return the value of tbl_kupai_notify.ch_key
     *
     * @mbggenerated
     */
    public String getChKey() {
        return chKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_kupai_notify.ch_key
     *
     * @param chKey the value for tbl_kupai_notify.ch_key
     *
     * @mbggenerated
     */
    public void setChKey(String chKey) {
        this.chKey = chKey == null ? null : chKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_kupai_notify.msg
     *
     * @return the value of tbl_kupai_notify.msg
     *
     * @mbggenerated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_kupai_notify.msg
     *
     * @param msg the value for tbl_kupai_notify.msg
     *
     * @mbggenerated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_kupai_notify.create_time
     *
     * @return the value of tbl_kupai_notify.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_kupai_notify.create_time
     *
     * @param createTime the value for tbl_kupai_notify.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_kupai_notify.update_time
     *
     * @return the value of tbl_kupai_notify.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_kupai_notify.update_time
     *
     * @param updateTime the value for tbl_kupai_notify.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}