package com.sky.mobile.protocol.domain;

import java.util.Date;

public class OppNotify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_opp_notify.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_opp_notify.notify_id
     *
     * @mbggenerated
     */
    private String notifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_opp_notify.partner_order
     *
     * @mbggenerated
     */
    private String partnerOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_opp_notify.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_opp_notify.product_desc
     *
     * @mbggenerated
     */
    private String productDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_opp_notify.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_opp_notify.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_opp_notify.attach
     *
     * @mbggenerated
     */
    private String attach;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_opp_notify.sign
     *
     * @mbggenerated
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_opp_notify.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_opp_notify.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_opp_notify.id
     *
     * @return the value of tbl_opp_notify.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_opp_notify.id
     *
     * @param id the value for tbl_opp_notify.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_opp_notify.notify_id
     *
     * @return the value of tbl_opp_notify.notify_id
     *
     * @mbggenerated
     */
    public String getNotifyId() {
        return notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_opp_notify.notify_id
     *
     * @param notifyId the value for tbl_opp_notify.notify_id
     *
     * @mbggenerated
     */
    public void setNotifyId(String notifyId) {
        this.notifyId = notifyId == null ? null : notifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_opp_notify.partner_order
     *
     * @return the value of tbl_opp_notify.partner_order
     *
     * @mbggenerated
     */
    public String getPartnerOrder() {
        return partnerOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_opp_notify.partner_order
     *
     * @param partnerOrder the value for tbl_opp_notify.partner_order
     *
     * @mbggenerated
     */
    public void setPartnerOrder(String partnerOrder) {
        this.partnerOrder = partnerOrder == null ? null : partnerOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_opp_notify.product_name
     *
     * @return the value of tbl_opp_notify.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_opp_notify.product_name
     *
     * @param productName the value for tbl_opp_notify.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_opp_notify.product_desc
     *
     * @return the value of tbl_opp_notify.product_desc
     *
     * @mbggenerated
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_opp_notify.product_desc
     *
     * @param productDesc the value for tbl_opp_notify.product_desc
     *
     * @mbggenerated
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc == null ? null : productDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_opp_notify.price
     *
     * @return the value of tbl_opp_notify.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_opp_notify.price
     *
     * @param price the value for tbl_opp_notify.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_opp_notify.count
     *
     * @return the value of tbl_opp_notify.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_opp_notify.count
     *
     * @param count the value for tbl_opp_notify.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_opp_notify.attach
     *
     * @return the value of tbl_opp_notify.attach
     *
     * @mbggenerated
     */
    public String getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_opp_notify.attach
     *
     * @param attach the value for tbl_opp_notify.attach
     *
     * @mbggenerated
     */
    public void setAttach(String attach) {
        this.attach = attach == null ? null : attach.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_opp_notify.sign
     *
     * @return the value of tbl_opp_notify.sign
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_opp_notify.sign
     *
     * @param sign the value for tbl_opp_notify.sign
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_opp_notify.create_time
     *
     * @return the value of tbl_opp_notify.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_opp_notify.create_time
     *
     * @param createTime the value for tbl_opp_notify.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_opp_notify.update_time
     *
     * @return the value of tbl_opp_notify.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_opp_notify.update_time
     *
     * @param updateTime the value for tbl_opp_notify.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}