package com.sky.mobile.protocol.domain;

import java.util.Date;

public class Qqnotify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_qq_notify.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_qq_notify.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_qq_notify.appid
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_qq_notify.ts
     *
     * @mbggenerated
     */
    private String ts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_qq_notify.payitem
     *
     * @mbggenerated
     */
    private String payitem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_qq_notify.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_qq_notify.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_qq_notify.billno
     *
     * @mbggenerated
     */
    private String billno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_qq_notify.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_qq_notify.zoneid
     *
     * @mbggenerated
     */
    private String zoneid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_qq_notify.providetype
     *
     * @mbggenerated
     */
    private String providetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_qq_notify.amt
     *
     * @mbggenerated
     */
    private String amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_qq_notify.payamt_coins
     *
     * @mbggenerated
     */
    private String payamtCoins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_qq_notify.pubacct_payamt_coins
     *
     * @mbggenerated
     */
    private String pubacctPayamtCoins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_qq_notify.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_qq_notify.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_qq_notify.id
     *
     * @return the value of tbl_qq_notify.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_qq_notify.id
     *
     * @param id the value for tbl_qq_notify.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_qq_notify.openid
     *
     * @return the value of tbl_qq_notify.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_qq_notify.openid
     *
     * @param openid the value for tbl_qq_notify.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_qq_notify.appid
     *
     * @return the value of tbl_qq_notify.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_qq_notify.appid
     *
     * @param appid the value for tbl_qq_notify.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_qq_notify.ts
     *
     * @return the value of tbl_qq_notify.ts
     *
     * @mbggenerated
     */
    public String getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_qq_notify.ts
     *
     * @param ts the value for tbl_qq_notify.ts
     *
     * @mbggenerated
     */
    public void setTs(String ts) {
        this.ts = ts == null ? null : ts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_qq_notify.payitem
     *
     * @return the value of tbl_qq_notify.payitem
     *
     * @mbggenerated
     */
    public String getPayitem() {
        return payitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_qq_notify.payitem
     *
     * @param payitem the value for tbl_qq_notify.payitem
     *
     * @mbggenerated
     */
    public void setPayitem(String payitem) {
        this.payitem = payitem == null ? null : payitem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_qq_notify.order_id
     *
     * @return the value of tbl_qq_notify.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_qq_notify.order_id
     *
     * @param orderId the value for tbl_qq_notify.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_qq_notify.token
     *
     * @return the value of tbl_qq_notify.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_qq_notify.token
     *
     * @param token the value for tbl_qq_notify.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_qq_notify.billno
     *
     * @return the value of tbl_qq_notify.billno
     *
     * @mbggenerated
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_qq_notify.billno
     *
     * @param billno the value for tbl_qq_notify.billno
     *
     * @mbggenerated
     */
    public void setBillno(String billno) {
        this.billno = billno == null ? null : billno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_qq_notify.version
     *
     * @return the value of tbl_qq_notify.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_qq_notify.version
     *
     * @param version the value for tbl_qq_notify.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_qq_notify.zoneid
     *
     * @return the value of tbl_qq_notify.zoneid
     *
     * @mbggenerated
     */
    public String getZoneid() {
        return zoneid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_qq_notify.zoneid
     *
     * @param zoneid the value for tbl_qq_notify.zoneid
     *
     * @mbggenerated
     */
    public void setZoneid(String zoneid) {
        this.zoneid = zoneid == null ? null : zoneid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_qq_notify.providetype
     *
     * @return the value of tbl_qq_notify.providetype
     *
     * @mbggenerated
     */
    public String getProvidetype() {
        return providetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_qq_notify.providetype
     *
     * @param providetype the value for tbl_qq_notify.providetype
     *
     * @mbggenerated
     */
    public void setProvidetype(String providetype) {
        this.providetype = providetype == null ? null : providetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_qq_notify.amt
     *
     * @return the value of tbl_qq_notify.amt
     *
     * @mbggenerated
     */
    public String getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_qq_notify.amt
     *
     * @param amt the value for tbl_qq_notify.amt
     *
     * @mbggenerated
     */
    public void setAmt(String amt) {
        this.amt = amt == null ? null : amt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_qq_notify.payamt_coins
     *
     * @return the value of tbl_qq_notify.payamt_coins
     *
     * @mbggenerated
     */
    public String getPayamtCoins() {
        return payamtCoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_qq_notify.payamt_coins
     *
     * @param payamtCoins the value for tbl_qq_notify.payamt_coins
     *
     * @mbggenerated
     */
    public void setPayamtCoins(String payamtCoins) {
        this.payamtCoins = payamtCoins == null ? null : payamtCoins.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_qq_notify.pubacct_payamt_coins
     *
     * @return the value of tbl_qq_notify.pubacct_payamt_coins
     *
     * @mbggenerated
     */
    public String getPubacctPayamtCoins() {
        return pubacctPayamtCoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_qq_notify.pubacct_payamt_coins
     *
     * @param pubacctPayamtCoins the value for tbl_qq_notify.pubacct_payamt_coins
     *
     * @mbggenerated
     */
    public void setPubacctPayamtCoins(String pubacctPayamtCoins) {
        this.pubacctPayamtCoins = pubacctPayamtCoins == null ? null : pubacctPayamtCoins.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_qq_notify.update_time
     *
     * @return the value of tbl_qq_notify.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_qq_notify.update_time
     *
     * @param updateTime the value for tbl_qq_notify.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_qq_notify.create_time
     *
     * @return the value of tbl_qq_notify.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_qq_notify.create_time
     *
     * @param createTime the value for tbl_qq_notify.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}