package com.sky.mobile.protocol.domain;

import java.util.Date;

public class SafeCenterNotify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_safe_center_notify.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_safe_center_notify.app_key
     *
     * @mbggenerated
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_safe_center_notify.product_id
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_safe_center_notify.amount
     *
     * @mbggenerated
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_safe_center_notify.app_uid
     *
     * @mbggenerated
     */
    private String appUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_safe_center_notify.app_ext1
     *
     * @mbggenerated
     */
    private String appExt1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_safe_center_notify.app_ext2
     *
     * @mbggenerated
     */
    private String appExt2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_safe_center_notify.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_safe_center_notify.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_safe_center_notify.gateway_flag
     *
     * @mbggenerated
     */
    private String gatewayFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_safe_center_notify.sign_type
     *
     * @mbggenerated
     */
    private String signType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_safe_center_notify.sign_return
     *
     * @mbggenerated
     */
    private String signReturn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_safe_center_notify.sign
     *
     * @mbggenerated
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_safe_center_notify.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_safe_center_notify.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_safe_center_notify.id
     *
     * @return the value of tbl_safe_center_notify.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_safe_center_notify.id
     *
     * @param id the value for tbl_safe_center_notify.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_safe_center_notify.app_key
     *
     * @return the value of tbl_safe_center_notify.app_key
     *
     * @mbggenerated
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_safe_center_notify.app_key
     *
     * @param appKey the value for tbl_safe_center_notify.app_key
     *
     * @mbggenerated
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_safe_center_notify.product_id
     *
     * @return the value of tbl_safe_center_notify.product_id
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_safe_center_notify.product_id
     *
     * @param productId the value for tbl_safe_center_notify.product_id
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_safe_center_notify.amount
     *
     * @return the value of tbl_safe_center_notify.amount
     *
     * @mbggenerated
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_safe_center_notify.amount
     *
     * @param amount the value for tbl_safe_center_notify.amount
     *
     * @mbggenerated
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_safe_center_notify.app_uid
     *
     * @return the value of tbl_safe_center_notify.app_uid
     *
     * @mbggenerated
     */
    public String getAppUid() {
        return appUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_safe_center_notify.app_uid
     *
     * @param appUid the value for tbl_safe_center_notify.app_uid
     *
     * @mbggenerated
     */
    public void setAppUid(String appUid) {
        this.appUid = appUid == null ? null : appUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_safe_center_notify.app_ext1
     *
     * @return the value of tbl_safe_center_notify.app_ext1
     *
     * @mbggenerated
     */
    public String getAppExt1() {
        return appExt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_safe_center_notify.app_ext1
     *
     * @param appExt1 the value for tbl_safe_center_notify.app_ext1
     *
     * @mbggenerated
     */
    public void setAppExt1(String appExt1) {
        this.appExt1 = appExt1 == null ? null : appExt1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_safe_center_notify.app_ext2
     *
     * @return the value of tbl_safe_center_notify.app_ext2
     *
     * @mbggenerated
     */
    public String getAppExt2() {
        return appExt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_safe_center_notify.app_ext2
     *
     * @param appExt2 the value for tbl_safe_center_notify.app_ext2
     *
     * @mbggenerated
     */
    public void setAppExt2(String appExt2) {
        this.appExt2 = appExt2 == null ? null : appExt2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_safe_center_notify.user_id
     *
     * @return the value of tbl_safe_center_notify.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_safe_center_notify.user_id
     *
     * @param userId the value for tbl_safe_center_notify.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_safe_center_notify.order_id
     *
     * @return the value of tbl_safe_center_notify.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_safe_center_notify.order_id
     *
     * @param orderId the value for tbl_safe_center_notify.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_safe_center_notify.gateway_flag
     *
     * @return the value of tbl_safe_center_notify.gateway_flag
     *
     * @mbggenerated
     */
    public String getGatewayFlag() {
        return gatewayFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_safe_center_notify.gateway_flag
     *
     * @param gatewayFlag the value for tbl_safe_center_notify.gateway_flag
     *
     * @mbggenerated
     */
    public void setGatewayFlag(String gatewayFlag) {
        this.gatewayFlag = gatewayFlag == null ? null : gatewayFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_safe_center_notify.sign_type
     *
     * @return the value of tbl_safe_center_notify.sign_type
     *
     * @mbggenerated
     */
    public String getSignType() {
        return signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_safe_center_notify.sign_type
     *
     * @param signType the value for tbl_safe_center_notify.sign_type
     *
     * @mbggenerated
     */
    public void setSignType(String signType) {
        this.signType = signType == null ? null : signType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_safe_center_notify.sign_return
     *
     * @return the value of tbl_safe_center_notify.sign_return
     *
     * @mbggenerated
     */
    public String getSignReturn() {
        return signReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_safe_center_notify.sign_return
     *
     * @param signReturn the value for tbl_safe_center_notify.sign_return
     *
     * @mbggenerated
     */
    public void setSignReturn(String signReturn) {
        this.signReturn = signReturn == null ? null : signReturn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_safe_center_notify.sign
     *
     * @return the value of tbl_safe_center_notify.sign
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_safe_center_notify.sign
     *
     * @param sign the value for tbl_safe_center_notify.sign
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_safe_center_notify.create_time
     *
     * @return the value of tbl_safe_center_notify.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_safe_center_notify.create_time
     *
     * @param createTime the value for tbl_safe_center_notify.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_safe_center_notify.update_time
     *
     * @return the value of tbl_safe_center_notify.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_safe_center_notify.update_time
     *
     * @param updateTime the value for tbl_safe_center_notify.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}