package com.sky.mobile.protocol.domain;

import java.math.BigDecimal;
import java.util.Date;

public class VivoGetOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_vivo_get_order.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_vivo_get_order.order_time
     *
     * @mbggenerated
     */
    private String orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_vivo_get_order.order_amount
     *
     * @mbggenerated
     */
    private BigDecimal orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_vivo_get_order.order_title
     *
     * @mbggenerated
     */
    private String orderTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_vivo_get_order.order_description
     *
     * @mbggenerated
     */
    private String orderDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_vivo_get_order.vivo_order
     *
     * @mbggenerated
     */
    private String vivoOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_vivo_get_order.vivo_signature
     *
     * @mbggenerated
     */
    private String vivoSignature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_vivo_get_order.local_order_id
     *
     * @mbggenerated
     */
    private String localOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_vivo_get_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_vivo_get_order.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_vivo_get_order.id
     *
     * @return the value of tbl_vivo_get_order.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_vivo_get_order.id
     *
     * @param id the value for tbl_vivo_get_order.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_vivo_get_order.order_time
     *
     * @return the value of tbl_vivo_get_order.order_time
     *
     * @mbggenerated
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_vivo_get_order.order_time
     *
     * @param orderTime the value for tbl_vivo_get_order.order_time
     *
     * @mbggenerated
     */
    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime == null ? null : orderTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_vivo_get_order.order_amount
     *
     * @return the value of tbl_vivo_get_order.order_amount
     *
     * @mbggenerated
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_vivo_get_order.order_amount
     *
     * @param orderAmount the value for tbl_vivo_get_order.order_amount
     *
     * @mbggenerated
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_vivo_get_order.order_title
     *
     * @return the value of tbl_vivo_get_order.order_title
     *
     * @mbggenerated
     */
    public String getOrderTitle() {
        return orderTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_vivo_get_order.order_title
     *
     * @param orderTitle the value for tbl_vivo_get_order.order_title
     *
     * @mbggenerated
     */
    public void setOrderTitle(String orderTitle) {
        this.orderTitle = orderTitle == null ? null : orderTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_vivo_get_order.order_description
     *
     * @return the value of tbl_vivo_get_order.order_description
     *
     * @mbggenerated
     */
    public String getOrderDescription() {
        return orderDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_vivo_get_order.order_description
     *
     * @param orderDescription the value for tbl_vivo_get_order.order_description
     *
     * @mbggenerated
     */
    public void setOrderDescription(String orderDescription) {
        this.orderDescription = orderDescription == null ? null : orderDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_vivo_get_order.vivo_order
     *
     * @return the value of tbl_vivo_get_order.vivo_order
     *
     * @mbggenerated
     */
    public String getVivoOrder() {
        return vivoOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_vivo_get_order.vivo_order
     *
     * @param vivoOrder the value for tbl_vivo_get_order.vivo_order
     *
     * @mbggenerated
     */
    public void setVivoOrder(String vivoOrder) {
        this.vivoOrder = vivoOrder == null ? null : vivoOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_vivo_get_order.vivo_signature
     *
     * @return the value of tbl_vivo_get_order.vivo_signature
     *
     * @mbggenerated
     */
    public String getVivoSignature() {
        return vivoSignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_vivo_get_order.vivo_signature
     *
     * @param vivoSignature the value for tbl_vivo_get_order.vivo_signature
     *
     * @mbggenerated
     */
    public void setVivoSignature(String vivoSignature) {
        this.vivoSignature = vivoSignature == null ? null : vivoSignature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_vivo_get_order.local_order_id
     *
     * @return the value of tbl_vivo_get_order.local_order_id
     *
     * @mbggenerated
     */
    public String getLocalOrderId() {
        return localOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_vivo_get_order.local_order_id
     *
     * @param localOrderId the value for tbl_vivo_get_order.local_order_id
     *
     * @mbggenerated
     */
    public void setLocalOrderId(String localOrderId) {
        this.localOrderId = localOrderId == null ? null : localOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_vivo_get_order.create_time
     *
     * @return the value of tbl_vivo_get_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_vivo_get_order.create_time
     *
     * @param createTime the value for tbl_vivo_get_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_vivo_get_order.update_time
     *
     * @return the value of tbl_vivo_get_order.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_vivo_get_order.update_time
     *
     * @param updateTime the value for tbl_vivo_get_order.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}