package com.sky.mobile.protocol.domain;

import java.util.Date;

public class WdjNotify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wdj_notify.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wdj_notify.wdj_timestamp
     *
     * @mbggenerated
     */
    private String wdjTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wdj_notify.money
     *
     * @mbggenerated
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wdj_notify.charge_type
     *
     * @mbggenerated
     */
    private String chargeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wdj_notify.app_key_id
     *
     * @mbggenerated
     */
    private String appKeyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wdj_notify.buyer_id
     *
     * @mbggenerated
     */
    private String buyerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wdj_notify.out_trade_no
     *
     * @mbggenerated
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wdj_notify.card_no
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wdj_notify.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wdj_notify.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wdj_notify.id
     *
     * @return the value of tbl_wdj_notify.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wdj_notify.id
     *
     * @param id the value for tbl_wdj_notify.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wdj_notify.wdj_timestamp
     *
     * @return the value of tbl_wdj_notify.wdj_timestamp
     *
     * @mbggenerated
     */
    public String getWdjTimestamp() {
        return wdjTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wdj_notify.wdj_timestamp
     *
     * @param wdjTimestamp the value for tbl_wdj_notify.wdj_timestamp
     *
     * @mbggenerated
     */
    public void setWdjTimestamp(String wdjTimestamp) {
        this.wdjTimestamp = wdjTimestamp == null ? null : wdjTimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wdj_notify.money
     *
     * @return the value of tbl_wdj_notify.money
     *
     * @mbggenerated
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wdj_notify.money
     *
     * @param money the value for tbl_wdj_notify.money
     *
     * @mbggenerated
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wdj_notify.charge_type
     *
     * @return the value of tbl_wdj_notify.charge_type
     *
     * @mbggenerated
     */
    public String getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wdj_notify.charge_type
     *
     * @param chargeType the value for tbl_wdj_notify.charge_type
     *
     * @mbggenerated
     */
    public void setChargeType(String chargeType) {
        this.chargeType = chargeType == null ? null : chargeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wdj_notify.app_key_id
     *
     * @return the value of tbl_wdj_notify.app_key_id
     *
     * @mbggenerated
     */
    public String getAppKeyId() {
        return appKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wdj_notify.app_key_id
     *
     * @param appKeyId the value for tbl_wdj_notify.app_key_id
     *
     * @mbggenerated
     */
    public void setAppKeyId(String appKeyId) {
        this.appKeyId = appKeyId == null ? null : appKeyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wdj_notify.buyer_id
     *
     * @return the value of tbl_wdj_notify.buyer_id
     *
     * @mbggenerated
     */
    public String getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wdj_notify.buyer_id
     *
     * @param buyerId the value for tbl_wdj_notify.buyer_id
     *
     * @mbggenerated
     */
    public void setBuyerId(String buyerId) {
        this.buyerId = buyerId == null ? null : buyerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wdj_notify.out_trade_no
     *
     * @return the value of tbl_wdj_notify.out_trade_no
     *
     * @mbggenerated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wdj_notify.out_trade_no
     *
     * @param outTradeNo the value for tbl_wdj_notify.out_trade_no
     *
     * @mbggenerated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wdj_notify.card_no
     *
     * @return the value of tbl_wdj_notify.card_no
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wdj_notify.card_no
     *
     * @param cardNo the value for tbl_wdj_notify.card_no
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wdj_notify.create_time
     *
     * @return the value of tbl_wdj_notify.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wdj_notify.create_time
     *
     * @param createTime the value for tbl_wdj_notify.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wdj_notify.update_time
     *
     * @return the value of tbl_wdj_notify.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wdj_notify.update_time
     *
     * @param updateTime the value for tbl_wdj_notify.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}