package com.sky.mobile.protocol.domain;

import java.util.Date;

public class YoukuNotify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_youku_notify.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_youku_notify.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_youku_notify.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_youku_notify.local_order_id
     *
     * @mbggenerated
     */
    private String localOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_youku_notify.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_youku_notify.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_youku_notify.id
     *
     * @return the value of tbl_youku_notify.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_youku_notify.id
     *
     * @param id the value for tbl_youku_notify.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_youku_notify.order_id
     *
     * @return the value of tbl_youku_notify.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_youku_notify.order_id
     *
     * @param orderId the value for tbl_youku_notify.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_youku_notify.price
     *
     * @return the value of tbl_youku_notify.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_youku_notify.price
     *
     * @param price the value for tbl_youku_notify.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_youku_notify.local_order_id
     *
     * @return the value of tbl_youku_notify.local_order_id
     *
     * @mbggenerated
     */
    public String getLocalOrderId() {
        return localOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_youku_notify.local_order_id
     *
     * @param localOrderId the value for tbl_youku_notify.local_order_id
     *
     * @mbggenerated
     */
    public void setLocalOrderId(String localOrderId) {
        this.localOrderId = localOrderId == null ? null : localOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_youku_notify.update_time
     *
     * @return the value of tbl_youku_notify.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_youku_notify.update_time
     *
     * @param updateTime the value for tbl_youku_notify.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_youku_notify.create_time
     *
     * @return the value of tbl_youku_notify.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_youku_notify.create_time
     *
     * @param createTime the value for tbl_youku_notify.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}