package com.toyo.fish.data.wrapper.friends.domain;

import java.util.Date;

public class Friends {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friends.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friends.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friends.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friends.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friends.last_access_time
     *
     * @mbggenerated
     */
    private Date lastAccessTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friends.max_friends
     *
     * @mbggenerated
     */
    private Integer maxFriends;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friends.current_friends
     *
     * @mbggenerated
     */
    private Integer currentFriends;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friends.max_friends_reuqest
     *
     * @mbggenerated
     */
    private Integer maxFriendsReuqest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friends.current_friends_request
     *
     * @mbggenerated
     */
    private Integer currentFriendsRequest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friends.max_give_vit
     *
     * @mbggenerated
     */
    private Integer maxGiveVit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friends.current_give_vit
     *
     * @mbggenerated
     */
    private Integer currentGiveVit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friends.max_get_vit
     *
     * @mbggenerated
     */
    private Integer maxGetVit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friends.current_get_vit
     *
     * @mbggenerated
     */
    private Integer currentGetVit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friends.last_refresh_recomment_friends
     *
     * @mbggenerated
     */
    private Date lastRefreshRecommentFriends;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friends.avatar
     *
     * @mbggenerated
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friends.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friends.user_level
     *
     * @mbggenerated
     */
    private Integer userLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friends.id
     *
     * @return the value of ty_friends.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friends.id
     *
     * @param id the value for ty_friends.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friends.update_time
     *
     * @return the value of ty_friends.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friends.update_time
     *
     * @param updateTime the value for ty_friends.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friends.create_time
     *
     * @return the value of ty_friends.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friends.create_time
     *
     * @param createTime the value for ty_friends.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friends.user_id
     *
     * @return the value of ty_friends.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friends.user_id
     *
     * @param userId the value for ty_friends.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friends.last_access_time
     *
     * @return the value of ty_friends.last_access_time
     *
     * @mbggenerated
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friends.last_access_time
     *
     * @param lastAccessTime the value for ty_friends.last_access_time
     *
     * @mbggenerated
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friends.max_friends
     *
     * @return the value of ty_friends.max_friends
     *
     * @mbggenerated
     */
    public Integer getMaxFriends() {
        return maxFriends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friends.max_friends
     *
     * @param maxFriends the value for ty_friends.max_friends
     *
     * @mbggenerated
     */
    public void setMaxFriends(Integer maxFriends) {
        this.maxFriends = maxFriends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friends.current_friends
     *
     * @return the value of ty_friends.current_friends
     *
     * @mbggenerated
     */
    public Integer getCurrentFriends() {
        return currentFriends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friends.current_friends
     *
     * @param currentFriends the value for ty_friends.current_friends
     *
     * @mbggenerated
     */
    public void setCurrentFriends(Integer currentFriends) {
        this.currentFriends = currentFriends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friends.max_friends_reuqest
     *
     * @return the value of ty_friends.max_friends_reuqest
     *
     * @mbggenerated
     */
    public Integer getMaxFriendsReuqest() {
        return maxFriendsReuqest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friends.max_friends_reuqest
     *
     * @param maxFriendsReuqest the value for ty_friends.max_friends_reuqest
     *
     * @mbggenerated
     */
    public void setMaxFriendsReuqest(Integer maxFriendsReuqest) {
        this.maxFriendsReuqest = maxFriendsReuqest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friends.current_friends_request
     *
     * @return the value of ty_friends.current_friends_request
     *
     * @mbggenerated
     */
    public Integer getCurrentFriendsRequest() {
        return currentFriendsRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friends.current_friends_request
     *
     * @param currentFriendsRequest the value for ty_friends.current_friends_request
     *
     * @mbggenerated
     */
    public void setCurrentFriendsRequest(Integer currentFriendsRequest) {
        this.currentFriendsRequest = currentFriendsRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friends.max_give_vit
     *
     * @return the value of ty_friends.max_give_vit
     *
     * @mbggenerated
     */
    public Integer getMaxGiveVit() {
        return maxGiveVit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friends.max_give_vit
     *
     * @param maxGiveVit the value for ty_friends.max_give_vit
     *
     * @mbggenerated
     */
    public void setMaxGiveVit(Integer maxGiveVit) {
        this.maxGiveVit = maxGiveVit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friends.current_give_vit
     *
     * @return the value of ty_friends.current_give_vit
     *
     * @mbggenerated
     */
    public Integer getCurrentGiveVit() {
        return currentGiveVit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friends.current_give_vit
     *
     * @param currentGiveVit the value for ty_friends.current_give_vit
     *
     * @mbggenerated
     */
    public void setCurrentGiveVit(Integer currentGiveVit) {
        this.currentGiveVit = currentGiveVit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friends.max_get_vit
     *
     * @return the value of ty_friends.max_get_vit
     *
     * @mbggenerated
     */
    public Integer getMaxGetVit() {
        return maxGetVit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friends.max_get_vit
     *
     * @param maxGetVit the value for ty_friends.max_get_vit
     *
     * @mbggenerated
     */
    public void setMaxGetVit(Integer maxGetVit) {
        this.maxGetVit = maxGetVit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friends.current_get_vit
     *
     * @return the value of ty_friends.current_get_vit
     *
     * @mbggenerated
     */
    public Integer getCurrentGetVit() {
        return currentGetVit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friends.current_get_vit
     *
     * @param currentGetVit the value for ty_friends.current_get_vit
     *
     * @mbggenerated
     */
    public void setCurrentGetVit(Integer currentGetVit) {
        this.currentGetVit = currentGetVit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friends.last_refresh_recomment_friends
     *
     * @return the value of ty_friends.last_refresh_recomment_friends
     *
     * @mbggenerated
     */
    public Date getLastRefreshRecommentFriends() {
        return lastRefreshRecommentFriends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friends.last_refresh_recomment_friends
     *
     * @param lastRefreshRecommentFriends the value for ty_friends.last_refresh_recomment_friends
     *
     * @mbggenerated
     */
    public void setLastRefreshRecommentFriends(Date lastRefreshRecommentFriends) {
        this.lastRefreshRecommentFriends = lastRefreshRecommentFriends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friends.avatar
     *
     * @return the value of ty_friends.avatar
     *
     * @mbggenerated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friends.avatar
     *
     * @param avatar the value for ty_friends.avatar
     *
     * @mbggenerated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friends.nick_name
     *
     * @return the value of ty_friends.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friends.nick_name
     *
     * @param nickName the value for ty_friends.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friends.user_level
     *
     * @return the value of ty_friends.user_level
     *
     * @mbggenerated
     */
    public Integer getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friends.user_level
     *
     * @param userLevel the value for ty_friends.user_level
     *
     * @mbggenerated
     */
    public void setUserLevel(Integer userLevel) {
        this.userLevel = userLevel;
    }
}