package com.toyo.fish.data.wrapper.friends.domain;

import java.util.Date;

public class FriendsMailTemplate implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 952117846236303454L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friend_mail_template.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friend_mail_template.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friend_mail_template.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friend_mail_template.mail_categroy
     *
     * @mbggenerated
     */
    private Integer mailCategroy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friend_mail_template.mail_title
     *
     * @mbggenerated
     */
    private String mailTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_friend_mail_template.mail_content
     *
     * @mbggenerated
     */
    private String mailContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friend_mail_template.id
     *
     * @return the value of ty_friend_mail_template.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friend_mail_template.id
     *
     * @param id the value for ty_friend_mail_template.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friend_mail_template.update_time
     *
     * @return the value of ty_friend_mail_template.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friend_mail_template.update_time
     *
     * @param updateTime the value for ty_friend_mail_template.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friend_mail_template.create_time
     *
     * @return the value of ty_friend_mail_template.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friend_mail_template.create_time
     *
     * @param createTime the value for ty_friend_mail_template.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friend_mail_template.mail_categroy
     *
     * @return the value of ty_friend_mail_template.mail_categroy
     *
     * @mbggenerated
     */
    public Integer getMailCategroy() {
        return mailCategroy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friend_mail_template.mail_categroy
     *
     * @param mailCategroy the value for ty_friend_mail_template.mail_categroy
     *
     * @mbggenerated
     */
    public void setMailCategroy(Integer mailCategroy) {
        this.mailCategroy = mailCategroy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friend_mail_template.mail_title
     *
     * @return the value of ty_friend_mail_template.mail_title
     *
     * @mbggenerated
     */
    public String getMailTitle() {
        return mailTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friend_mail_template.mail_title
     *
     * @param mailTitle the value for ty_friend_mail_template.mail_title
     *
     * @mbggenerated
     */
    public void setMailTitle(String mailTitle) {
        this.mailTitle = mailTitle == null ? null : mailTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_friend_mail_template.mail_content
     *
     * @return the value of ty_friend_mail_template.mail_content
     *
     * @mbggenerated
     */
    public String getMailContent() {
        return mailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_friend_mail_template.mail_content
     *
     * @param mailContent the value for ty_friend_mail_template.mail_content
     *
     * @mbggenerated
     */
    public void setMailContent(String mailContent) {
        this.mailContent = mailContent == null ? null : mailContent.trim();
    }
}