package com.toyo.fish.data.wrapper.friends.persistence;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.toyo.fish.data.wrapper.friends.domain.Friends;

public interface FriendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_friends
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);
    
    int deleteByUserId(@Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_friends
     *
     * @mbggenerated
     */
    int insert(Friends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_friends
     *
     * @mbggenerated
     */
    int insertSelective(Friends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_friends
     *
     * @mbggenerated
     */
    Friends selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_friends
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Friends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_friends
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Friends record);
    
   // int updateByUserId(Friends record);
    int updateByUserId(@Param("userId") Long userId,@Param("giveVit") Integer giveVit,@Param("getVit") Integer getVit,@Param("friends") Integer friends,@Param("friendsRequest") Integer friendsRequest);
    
    int updateByUserIds(@Param("userIdSeq") List<Long> userId,@Param("giveVit") Integer giveVit,@Param("getVit") Integer getVit,@Param("friends") Integer friends,@Param("friendsRequest") Integer friendsRequest);
    
    
    Friends selectByUserId(@Param("id") Long id);
    
    int updateFriendsRestrictions();
    
    
    int sizeOfRecommentFriends(@Param("userId") Long userId);
    List<Friends> getRecommentFriends();
   
    
    
    

}