package com.toyo.fish.data.wrapper.system.persistence;

import org.apache.ibatis.annotations.Param;

import com.toyo.fish.data.wrapper.system.domain.ExchangeCodeGift;

public interface ExchangeCodeGiftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_exchange_code_gift
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_exchange_code_gift
     *
     * @mbggenerated
     */
    int insert(ExchangeCodeGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_exchange_code_gift
     *
     * @mbggenerated
     */
    int insertSelective(ExchangeCodeGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_exchange_code_gift
     *
     * @mbggenerated
     */
    ExchangeCodeGift selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_exchange_code_gift
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExchangeCodeGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_exchange_code_gift
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExchangeCodeGift record);
    
    ExchangeCodeGift selectById(@Param("id") Integer id);
}