package com.toyo.fish.data.wrapper.system.persistence;

import com.toyo.fish.data.wrapper.system.domain.ResourceFiles;

public interface ResourceFilesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_resource_files
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_resource_files
     *
     * @mbggenerated
     */
    int insert(ResourceFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_resource_files
     *
     * @mbggenerated
     */
    int insertSelective(ResourceFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_resource_files
     *
     * @mbggenerated
     */
    ResourceFiles selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_resource_files
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ResourceFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_resource_files
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ResourceFiles record);
    
    
   // ResourceFiles selectByResourceUpdateId(Long resourceUpdateId );
}