package com.toyo.fish.data.wrapper.system.persistence;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.toyo.fish.data.wrapper.system.domain.ResourceUpdate;

public interface ResourceUpdateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_resource_update
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_resource_update
     *
     * @mbggenerated
     */
    int insert(ResourceUpdate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_resource_update
     *
     * @mbggenerated
     */
    int insertSelective(ResourceUpdate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_resource_update
     *
     * @mbggenerated
     */
    ResourceUpdate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_resource_update
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ResourceUpdate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_resource_update
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ResourceUpdate record);
    
    
    ResourceUpdate selectByChannelId(@Param("channelId")Integer channelId);
    
}