package com.toyo.fish.data.wrapper.system.persistence;

import org.apache.ibatis.annotations.Param;

import com.toyo.fish.data.wrapper.system.domain.UserGeneralExchangeCode;

public interface UserGeneralExchangeCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_user_general_exchange_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_user_general_exchange_code
     *
     * @mbggenerated
     */
    int insert(UserGeneralExchangeCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_user_general_exchange_code
     *
     * @mbggenerated
     */
    int insertSelective(UserGeneralExchangeCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_user_general_exchange_code
     *
     * @mbggenerated
     */
    UserGeneralExchangeCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_user_general_exchange_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserGeneralExchangeCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ty_user_general_exchange_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserGeneralExchangeCode record);
    
    UserGeneralExchangeCode  selectByGiftId(@Param("giftId") int giftId, @Param("userId") Long userId);
    int updateByGiftId(@Param("giftId") int giftId, @Param("userId") Long userId);

}